### ISSUE TITLE
Yieldly's Yieldly - COSG and COSG-COSG staking pools

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#10]
by kerrilija in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/966668590378024960)  
> please add cosg -> cosg, yldy -> cosg. just had a mini heart attack 😂

**Comment by AlgoRhythMatic** [comment]
Type: [F1]
Recipient: kerrilija (Discord) - 100%
