### ISSUE TITLE
Research $THC dApp

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#1011]
[F1] @flippingalgos 

https://app.thehighcommunity.net/

This dApp is created by @flippingalgos and we'd at least implement it as an NFT market/swap tool for tax reports collecting.

**Comment by ipaleka** [comment]
More info: https://www.flippingalgos.xyz/services.html

**Comment by flippingalgos** [comment]
fyi if you need any information or want me to customize or create any custom API endpoints or tag data on chain a specific way etc LMK happy to curate to get full support on asastats!!!

**Comment by flippingalgos** [comment]
specifically too NFT vault support would be awesome.. we apply a smart contract to a nft and then mint a vaultappid and vaultaddress on each nft.. so you can pull the vault appid /address lookup that address and view what asset(s) are owned by that nft

**Comment by ipaleka** [comment]
> fyi if you need any information or want me to customize or create any custom API endpoints or tag data on chain a specific way etc LMK happy to curate to get full support on asastats!!!

Hi and thank you for your response! :) I've created issue #1016 for your NFT vaults and I'll ask you eventual questions in that thread after the initial research.

Initial fetching of all the NFT purchases started a few days ago and will last a few more days. On top of [THC](https://allo.info/asset/1119722936/token/) listings and purchases, we have encountered some [$ASHES](https://allo.info/asset/1071265460/token/), [Feathers](https://allo.info/asset/1091143717/token/), and [ButtCoin](https://allo.info/asset/753137719/token/) listings and purchases, as well as some [GAS](https://allo.info/asset/1144340594/token/) purchases. Are we free to assume each token represents its own gallery/NFT market? If that's the case then only what we need for now - besides finished initial collecting - are the exact links to those galleries.

We have them for The High Community market, auctions are in the form:

`https://app.thehighcommunity.net/auction/{app_id}`

and listings:

`https://app.thehighcommunity.net/listing/{app_id}`

We link NFT purchases to a block explorer (allo,info only for now, after we implement user settings users will be able to pick the one they want).

**Comment by ipaleka** [comment]
> Are we free to assume each token represents its own gallery/NFT market?

P.S. Meanwhile, some [COOP](https://allo.info/asset/796425061/token/), [SOULS](https://allo.info/asset/1021797452/token/), and [Jimmy](https://allo.info/asset/511028589/token/) purchases have been collected too...

**Comment by ipaleka** [comment]
> $ASHES

https://algobones-dapp.vercel.app/market

> Feathers

https://billybigbeakd-app.vercel.app/marketplace

> GAS

https://www.tucantribe.xyz

> SOULS

https://market.spawnlings.com/

> Jimmy

https://www.jimcoin.app

> THICC

https://app.gully.farm/marketplace

**Comment by ipaleka** [comment]
> Jimmy

https://www.jimcoin.app ?

**Comment by ipaleka** [comment]
> $ASHES

https://algobones-dapp.vercel.app/market

**Comment by ipaleka** [comment]
Can you please help with the others @flippingalgos ? :)

P.S. Probably just with COOP market, as buttcoin.cc shows no market link.

P.P.S Meanwhile [THICC](https://allo.info/asset/1194470385/token/) auctions, listings, and purchases have been collected by our engine.

**Comment by ipaleka** [comment]
> GAS

https://www.tucantribe.xyz
