### ISSUE TITLE
Reported governance info is incorrect

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#1020]
Bug description:

I have two Pact pools that are part of governance and even though I voted, Stats shows: 

> No vote (Pact)

I verified the two addresses at: https://governance.algorand.foundation/governance-period-11/governors/$addr and it reports that these addresses have voted. 

The vanilla voting also incorrectly reports, no vote.

--------------------

Related: The heart link to https://www.algorandstats.com/governance-period-11/account/$addr opens a page that is blank. It seems they haven't made their P11 page yet.

**Comment by ipaleka** [comment]
I checked the address you've been using for rewards - that one has two Pact and one vanilla governance record - and all three entries say "eligible governor". Is it possible that you voted and checked in a period smaller than 10 minutes (our governance update cron script runs every 10 minutes)?

**Comment by ipaleka** [comment]
> Related: The heart link to https://www.algorandstats.com/governance-period-11/account/$addr opens a page that is blank. It seems they haven't made their P11 page yet.

I guess you're right as also the page for period 11 is blank: https://www.algorandstats.com/governance-period-11/, while home page redirects to https://www.algorandstats.com/governance-period-10.

**Comment by moloch10** [comment]
> I checked the address you've been using for rewards - that one has two Pact and one vanilla governance record - and all three entries say "eligible governor". Is it possible that you voted and checked in a period smaller than 10 minutes (our governance update cron script runs every 10 minutes)?

Yup, just checked and it shows correctly voted. I checked the time stamps against when I put the ticket in and the vanilla voting was about 20+ mins and the pools were just about 10 mins, either way, it's correct now. 😀
Thanks!

**Comment by ipaleka** [comment]
> > I checked the address you've been using for rewards - that one has two Pact and one vanilla governance record - and all three entries say "eligible governor". Is it possible that you voted and checked in a period smaller than 10 minutes (our governance update cron script runs every 10 minutes)?
> 
> Yup, just checked and it shows correctly voted. I checked the time stamps against when I put the ticket in and the vanilla voting was about 20+ mins and the pools were just about 10 mins, either way, it's correct now. 😀 Thanks!

Tbh, I should say I noticed the Foundation governance API was late once, half of a year ago or so, after a similar 20 or 30 minutes passed our cache was showing old data. I started to check where the bug starts and meanwhile, I guess, the Foundation updated the data.

I guess there's no point in decreasing our cron schedule to 5 minutes or so, let's stick to these 10 minutes...
