### ISSUE TITLE
[B2] Octorand's upgraded NFTs aren't recognized

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#1042]
Octorand recently upgraded their platform. All assets have been reminted to follow NFT standards that didn't exist when they were first minted.

After swapping the old version, the newly received asset is ignored on Stats. This applies to both gen 1 and gen 2.

**Comment by moloch10** [comment]
Gen 1 creator wallet: WLBZZ2XAUWBFUNSRL4GMU7FDIBY3WAT5VFXNLRJJX2G5RRT6JQMRKYNHFU
Gen 2 creator wallet: RFBPCQV6JFPUSBADUQBRF7575W2ZM4U5GIS37ZBKT5BZPEW22QR7WEZ53U

**Comment by moloch10** [comment]
Links have also been updated:
Gen 1: https://octorand.com/collection/prime/gen1/111
Gen 2: https://octorand.com/collection/prime/gen2/4444

**Comment by ipaleka** [comment]
This should be deployed tonight or tomorrow, though there are some doubts about implementation. First of all, my stance is that these new assets shouldn't inherit purchase data from the old assets (last or max) as these are the new NFTs and that has been ASA Stats policy. We'll add "Sales" (number of sales) property to metadata and that's it. Btw, the old assets purchases will be visible in the CSV reports for tax purposes and in the historic user widgets.

Another problem is that their website doesn't refresh new purchases so we won't have a proper checking mechanism.

**Comment by ipaleka** [comment]
> This should be deployed tonight or tomorrow, though there are some doubts about implementation. First of all, my stance is that these new assets shouldn't inherit purchase data from the old assets (last or max) as these are the new NFTs and that has been ASA Stats policy. We'll add "Sales" (number of sales) property to metadata and that's it. 

@moloch10 Let's say that my stance changed about this. :) The Octorand website (provider) sees them as the same but upgraded assets. What do you think?

**Comment by moloch10** [comment]
Oof. A new Id is a new Id but in this case, conceptually, they're the same. 

> The mission of ASA Stats is to become the primary source of price information for every ASA on the Algorand blockchain.

While the asset has switched, I think it should be treated as the same, to retain its original purchase date and price, so that the mission statement will be fulfilled. Otherwise the entire history of Octorand's price activity is lost.

**Comment by ipaleka** [comment]
Reopening until vaults are upgraded.
