### ISSUE TITLE
Links to AB2 Gallery listings should probably be removed

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#1043]
I was hunting for NFTs and found some that show they're listed for sale on AB2; but, it's been shut for a while. 

A typical buy this domain now page is shown.

Sample address: https://www.asastats.com/ASYQXGYTTFZA3T4THF2FAUDMNYS34X4JNEK4TISZBSZHDGLHRTBYCL2ENY

**Comment by ipaleka** [comment]
Oh, it was the biggest NFT market for quite a long time, until Rand Gallery surpassed it.

The problem with those links on our website is evident, tho we won't completely resolve the issue by just omitting the links: if we show those "Listed" links that implies the NFT is locked in an escrow (and that's a valid information if you ask me).

I guess the optimal solution would be to change the link text to "Escrowed by ab2.gallery" or something like that (feel free to provide your suggestion :) ). But to where the links should lead? Is there any solution for those users whose NFTs are listed there?

**Comment by moloch10** [comment]
> ... the NFT is locked in an escrow (and that's a valid information if you ask me).

I totally agree, it is valid information. "Escrowed by ab2.gallery" sounds good.  Maybe the link goes to the asset's allo page?

With the platform gone, I don't know if there's anything the owners can do.  This is probably right on an edge case too because many of the accounts / users from that time are dead.
