### ISSUE TITLE
After the Octorand upgrade, the original versions still show up

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#1046]
They're treated as Ⱥ0.10 valued assets so they're "hiding" at the bottom. 

The upgraded versions appear correctly with all the right values.  😀

**Comment by ipaleka** [comment]
> They're treated as Ⱥ0.10 valued assets so they're "hiding" at the bottom.

We still should decide if this is a bug or a feature! :grin: 

Those old NFTs are located inside the new dApps escrows and those escrows act as vaults. Maybe we can ignore them, just the way how Octorand UI doesn't show them as present in the vault on the related prime's page, but they are inside the escrow the owner has custody of.

You can see that the original issue had been reopened a few times, and one of the reasons was exactly this behavior. I initially thought there was a bug in our engine, but then I realized the old NFTs are indeed located in the escrow.

The Ocorand UI has some issues, for example you can't send ALGO right now from or to the vault (or I just can't find the way), so my stance was that maybe one day they will allow top move the old NFT out from the vault.
 
> The upgraded versions appear correctly with all the right values. 😀

:muscle:

**Comment by moloch10** [comment]
Got it. So even though they're still part of the escrow, I think they should be hidden. 

Since in the other ticket it was decided it's "the same" asset, even though it technically isn't, it shouldn't be shown twice because this is the new / upgraded version. 

What do you think?

**Comment by ipaleka** [comment]
> What do you think?

Well, I couldn't decide at first at that time and then I left them shown basically for a single selfish reason: I spent some time a few years ago on coding and creating those images from colored characters and I was happy with the result.  :sweat_smile:

**Comment by moloch10** [comment]
> > What do you think?
> 
> Well, I couldn't decide at first at that time and then I left them shown basically for a single selfish reason: I spent some time a few years ago on coding and creating those images from colored characters and I was happy with the result. 😅

This is a great reason, these look great and your efforts should not be wasted.

How about somehow combining them so instead of two Octorand Gen X sections, there's one and each prime shows both versions, maybe marked v1, v2? 

![image](https://github.com/user-attachments/assets/06fd6136-e3ae-4d09-9858-870c7ed5f31b)

**Comment by ipaleka** [comment]
That implies more coding for both the website and the mobile app as our code renders only a single image per NFT. We could go with an exception for the website, but I'm not sure how we can do that for the API and mobile app. In short, too much hassle for something that isn't of any real significance.

I guess the best solution is to just prevent showing those old NFTs in the vaults, while the related code could be maybe leveraged one day in some user widget, dunno...

**Comment by ipaleka** [comment]
Just to add something else, there are "similar" situations in the ecosystem, like Lofty AMM property tokens whose contracts ended. Those go under non-evaluated, while the plan is to move them all under "O-tens" collection. Such a collection consists of subcollections of assets worth exactly 0.1 ALGO (opt-in cost) no matter of amount, so maybe we can use those images inside that section.

**Comment by moloch10** [comment]
> That implies more coding for both the website and the mobile app as our code renders only a single image per NFT. We could go with an exception for the website, but I'm not sure how we can do that for the API and mobile app. In short, too much hassle for something that isn't of any real significance.
> 
> I guess the best solution is to just prevent showing those old NFTs in the vaults, while the related code could be maybe leveraged one day in some user widget, dunno...

Sounds like a lot of work for something that isn't nearly as needed as other features. Whatever you decide is best. 💪

**Comment by ipaleka** [comment]
The old assets found in vaults are not shown anymore. Just a side note: if users find a way to move them out of their vaults then they will show up.
