### ISSUE TITLE
[F1] Implement Lofty limit orders

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#1049]
[F1] 215j

Related issues: https://github.com/asastats/channel/issues/1041 https://github.com/asastats/channel/issues/1048

**Comment by AlgoRhythMatic** [comment]
Is there any rewardable item here?  Looks like issue #1041 has already been rewarded last cycle.

**Comment by ipaleka** [comment]
> Is there any rewardable item here? Looks like issue #1041 has already been rewarded last cycle.

Oh, sry, yes, I guess I wasn't sure what to do with this then.

As 215j has caused this too, I edited the body of this issue and added F1.
