### ISSUE TITLE
Fix tooltip position on checkbox in mobile view

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#1067]
Bug description:

In mobile version of ASA Stats website, checking the "Use maximum value engine" checkbox, the resulting tooltip, covers the process button.

https://github.com/user-attachments/assets/31112a88-f8ca-4a45-ba8c-8bed4a444291

**Comment by ipaleka** [comment]
Please check now. :)

**Comment by kerrilija** [comment]
All fine now :)
