### ISSUE TITLE
Update new Folks programs (was: Algo/USDc pact lp tokens 747244580 under NFT sectrion) 

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#114]
by tkpremier in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/981614772111958027):
> hey there, is it possible to get the deposit amount for folks.finance to show up?  i currently have algo/usdc pact lp tokens deposited there 
thank you, as always

**Comment by tkpremier** [comment]
from my app.folks.finance:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/11080301/171493353-b20d85ab-2a51-415d-afcc-c089425bcc43.png">

https://www.asastats.com/7D70AFD517DD77DB35604D1AD5BCAFA1B70CEC89
