### ISSUE TITLE
Add support for resolving named wallets (AlgoNameService & NFD support)

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#12]
https://discord.com/channels/906917846754418770/909644144635416626/933472191616516206

https://discord.com/channels/906917846754418770/909644144635416626/933726770404933662

https://discord.com/channels/906917846754418770/909644144635416626/933727667256168498

https://discord.com/channels/906917846754418770/909644144635416626/933728063974432798

**Comment by ipaleka** [comment]
Initial support for ANS has been added, by entering names registered by ANS into the address box on the index page.

It is expected that we add support for NFD names too once they launch on Mainnet, tho we don't know yet how we're going to deal with that.

I'm going to leave this issue open for a while, at least for the purpose of suggestions regarding implementing ANS for the URLs in the format `https://www.asastats.com/ans.name` too.

**Comment by ipaleka** [comment]
Support for ANS names directly in URL has also been added so I'm closing this issue and we'd eventually open some others for NFD.

**Comment by AlgoRhythMatic** [comment]
Type: [F2]
Recipient: DragMZ (Discord) - 100%
