### ISSUE TITLE
Project roadmap should be added in the homepage

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#14]
https://discord.com/channels/906917846754418770/908054304332603402/908322651041304606

Related comment in [ASA Stats About Page, Proposed Update](https://github.com/asastats/static-pages/issues/5#issuecomment-1106923697):
> Can we have a link to the [roadmap](https://github.com/asastats/docs/blob/main/roadmap.md) page?

**Comment by Zamanikings** [comment]
I think it should be added buy not on the homepage probably on the "ABOUT" page

**Comment by ipaleka** [comment]
Added to the About page: https://github.com/asastats/static-pages/issues/5

**Comment by AlgoRhythMatic** [comment]
Type: [S1]
Recipient: Mikeyy (Discord) - 100%
