### ISSUE TITLE
[Internal] Research and add Atomixwap as an NFT market

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#141]
https://github.com/asastats/channel/discussions/139#discussioncomment-2987663

**Comment by ipaleka** [comment]
https://github.com/asastats/channel/discussions/139#discussioncomment-2989280
- - - - -

> Afaic if someone has created a group transaction (an atomic swap) for an NFT that address holds, then for those [75 minutes](https://twitter.com/Atomixwap/status/1537360415872667650) after creation we can create a link to that atomic swap on Atomixwap.

I'm afraid this functionality isn't reachable to us by design. It seems that there are no database records at all as all the data needed is inside the link itself. That means the provider can't provide any API-like mechanism for us. 

Basically, even the creator can't get access to the future atomic swap if they lose the link, they have to create it again.

Still, after the targeted party signs a group transaction, it is, of course, available onchain and we have to [implement Atomixwap](https://github.com/asastats/channel/issues/141) as an NFT market having only purchases, without current listings.

**Comment by AlgoRhythMatic** [comment]
No reward assignment needed.
