### ISSUE TITLE
[B3] Liquidation in Folks is not shown

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#149]
by u/Reems81 on [Reddit](https://www.reddit.com/r/asastats/comments/vjw85x/fixing_asastat_wallet_page/):

> I'm unsure why it showed up now but I noticed my main wallet's page says that I still have a borrow from Folks Borrow. I was sadly liquidated during the Algo price crash and no longer have that borrow.

**Comment by AlgoRhythMatic** [comment]
Just a note (maybe to myself) that this is being tracked in the 2022-05-28 -> 2022-07-01 cycle, so should not be rewarded later after it is addressed.
