### ISSUE TITLE
Improved and inteligent 404 page

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#15]
https://discord.com/channels/906917846754418770/908054304332603402/917935473056428102
> A totally unneeded but "fun" suggestion. If someone enters an ETH or BTC or XXX address, it gives a "smart ass response." Basically acknowledging it's a valid address, just the wrong place or something like that

https://discord.com/channels/906917846754418770/908054304332603402/917942126204043326

Alos, the Server error 505 page should follow the same design.

**Comment by ipaleka** [comment]
We need some more ideas for this.

**Comment by Zamanikings** [comment]
Basically like a "that's a nice address you got there... But sorry we can't evaluate a non algorand address" 😌

**Comment by ipaleka** [comment]
> Basically like a "that's a nice address you got there... But sorry we can't evaluate a non algorand address" relieved

Yep, that sound nice, we should proofread that and come out with a final text.

That would be an example of entering a wrong value for xxxx in https://www.asastats.com/xxxx , while users can also point to https://www.asastats.com/about/me or https://www.asastats.com/tokenomics/ASASTATS and we should distinguish such an error from the first one.

Also, we need a similar design and approach for Server error 500 (just added to the initial comment).

**Comment by ipaleka** [comment]
Moved here: https://github.com/asastats/static-pages/issues/37
