### ISSUE TITLE
Last purchase time for an NFT is showing a negative number

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#154]
![image](https://user-images.githubusercontent.com/97535612/176512854-eea7ff94-09e8-49d2-beae-9722a1c4e9cf.png)

**Comment by moloch10** [comment]
Now the count is positive:
![image](https://user-images.githubusercontent.com/97535612/176518900-0d56c2f7-7105-4828-8085-79dd109d9a16.png)

Looks like this is happening with all that have been recently sold.

**Comment by ipaleka** [comment]
Please check if this occurs again.

**Comment by moloch10** [comment]
I have to wait until there's a sale of one of these or until the price is right and I'll buy one myself. I'm keeping an eye on it and will update.

**Comment by moloch10** [comment]
The time looks good for these two different ones. Although the amount for the second shows 1 ALGO when in fact it was sold for 7.
![image](https://user-images.githubusercontent.com/97535612/176810648-3305ef44-c053-4490-b7ee-486a8f67aa6b.png)

Here's the group txn for that sale: https://algoexplorer.io/tx/group/%2F0aPItSoO2OM%2F9gf7CUk6qQsfpMnQlviXwJxczlJlh8%3D

**Comment by ipaleka** [comment]
Ok, thanks, I'm closing this and will append the price problem to the existing issue.
