### ISSUE TITLE
[B2] Wrong NFT purchase prices

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#155]
We're going to have a bigger analysys and fixup.

Here are the example problems:

- - - - -
https://discord.com/channels/906917846754418770/908054330265960478/961212380904296459
Wrong last purchase price for FORUM Astro #\2
NFT: last purchase for FORUM Astro #\2 showing 25 ALGO, according to NFTexplorer = 55 ALGO on AlgoGems. Previous sale = 200 ALGO on ALGOxNFT

535631028

- - - - -

https://github.com/asastats/channel/issues/154#issuecomment-1171855303

The time looks good for these two different ones. Although the amount for the second shows 1 ALGO when in fact it was sold for 7.
![image](https://user-images.githubusercontent.com/97535612/176810648-3305ef44-c053-4490-b7ee-486a8f67aa6b.png)

Here's the group txn for that sale: https://algoexplorer.io/tx/group/%2F0aPItSoO2OM%2F9gf7CUk6qQsfpMnQlviXwJxczlJlh8%3D

- - - - -

**Comment by AlgoRhythMatic** [comment]
I also have some examples of incorrect "Last Purchase" dates for the Pera Governance NFT series (data from ALGOxNFT) - please let me know if it is helpful to add here.  I was not sure if incorrect date was also part of this scope.  In my example, the relative price is correct...it is just not the most recent "Last Purchase" example.

**Comment by ipaleka** [comment]
Weel, in parallel with API development that starts this week, we're going to bugfix the problems with the NFT Alpha version. You may provide assets' IDs here if you want.

**Comment by ipaleka** [comment]
NFT engine update deployment goes on Monday, after that all the purchase entries should fit. If not, we'll analyze every reported wrong entry in its dedicated issue.
