### ISSUE TITLE
Display ASA balance in native token, not only Algo

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#16]
https://discord.com/channels/906917846754418770/915342738201931836/934726027148664892
> For ASAs that are held across Balance, LP, Staking, Lending, etc., ASA Stats only shows the available balance using ALGO conversion, and not in the token unit. This could be improved by also showing the actual number of tokens (see example screenshot).

**Comment by AlgoRhythMatic** [comment]
Type: [F2]
Recipient: mynameis47 (Discord) - 50%
Note: RandomTask's share was tracked in a separate Trello card.
