### ISSUE TITLE
[B2] Links to some NFTs are incorrect

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#162]
NFT: 671977571
The link on Stats is: `https://gateway.pinata.cloud/ipfs/QmYrCCDGkG9QQouBm2wbNN1q2eLrC9BG35aQ1pEmD826w3`
Which shows a JSON dump of
`{"name":"Tinygotchi","description":"Tinygotchi - Tinyman. 15000 Tinygotchi NFTs are minted for the Tinyman compensation program. Only users who hold this item in their account will be able to benefit from future advantages of the compensation program.","decimals":0,"unitName":"tinygotc","image":"ipfs://QmQsDzyMLybctLZpBBHZKtrNTKhmvYbgVGb5APom8e25sa","image_mimetype":"image/png","animation_url":"ipfs://QmajCCjZfU7EaHsx3Ke5WUdmEqd5yy9KksKc6pnVkXjqCb","animation_url_mimetype":"video/mp4","properties":{}}`
When taking the value from image in the returned JSON string, `QmQsDzyMLybctLZpBBHZKtrNTKhmvYbgVGb5APom8e25sa` and using that in the URL, the correct image is rendered: `https://gateway.pinata.cloud/ipfs/QmQsDzyMLybctLZpBBHZKtrNTKhmvYbgVGb5APom8e25sa`

Here are two other assets I that have this similar bug: 727562141, 794772062. Looks like all the PeraWallet NFTs have this going on.
Here's a random address I found that has almost all of them:
https://www.asastats.com/Y67J57VAGI3QCL3SWZ5XHL6M
YF74XKVTUHJC2EPRUZ3Y4UNLG4MLG745T4
[I purposely broke up the address]

**Comment by ipaleka** [comment]
I guess the optimal solution would be to link that "QmajCCjZfU7EaHsx3Ke5WUdmEqd5yy9KksKc6pnVkXjqCb", respectively that we prioritize "animation_url" over "image" when found. And that goes for the other JSON keys, we should prioritize them, right?

**Comment by moloch10** [comment]
So before posting this ticket, I checked the `animation_url` value and for the PeraWallet NFTs, nothing loads up; I get a file download but I couldn't get it opened or see anything. When I tried the Tinygotchi, nothing happened at all, just hung. 

Now I tried the `animation_url` again for both and the PeraWallet NFTs again download a bogus file. However, this time, the Tinygotchi video did load up. 

> I guess the optimal solution would be to link that "QmajCCjZfU7EaHsx3Ke5WUdmEqd5yy9KksKc6pnVkXjqCb", respectively that we prioritize "animation_url" over "image" when found. And that goes for the other JSON keys, we should prioritize them, right?

I'm guessing that key is only available for NFTs that are animated? If that's the case, then I think that would probably be right.

**Comment by ipaleka** [comment]
Yes, if a JSON has that "animated_url" we use it, and a failback is to "image". Here's sorted properties by number of occurrences:

```
{
    "standard": 381537,
    "description": 303312,
    "properties": 234428,
    "mime_type": 218588,
    "external_url": 152569,
    "attributes": 116716,
    "name": 28784,
    "creator": 20922,
    "sensitive_content": 17494,
    "edition": 13700,
    "date": 10006,
    "dna": 10005,
    "media_url": 9829,
    "external_link": 9383,
    "kissBit_number": 5930,
    "image": 4195,
    "image_integrity": 4179,
    "id": 3300,
    "image_mimetype": 3101,
    "decimals": 2820,
    "unitName": 2820,
    "glyph": 2503,
    "assetName": 1555,
    "title": 1465,
    "royalties": 1085,
    "fileType": 1077,
    "editions": 1077,
    "asaInfo": 1077,
    "dartroomVersion": 1076,
    "extra_metadata": 890,
    "background_color": 822,
    "sentitiveContent": 577,
    "animation_url": 314,
    "animation_url_mimetype": 314,
    "animation_url_integrity": 305,
    "sensitiveContent": 275,
    "mime type": 107,
    "externalurl": 88,
    "external_url_integrity": 9,
    "external_url_mimetype": 9,
    "image_mime_type": 9,
    "rarity": 8,
    "commonality": 8,
    "run": 8,
    "range": 8,
    "filename": 8,
    "artist": 5,
    "creators_by": 5,
    "collection_series": 5,
    "collection_size": 5,
    "symbol": 3,
    "painting_url": 2,
    "painting_mime_type": 2,
    "screenshots": 2,
    "backdrop_color": 2,
    "history": 2,
    "artist_notes": 2,
    "backgroundColor": 1,
    "imageMimetype": 1,
    "imageIntegrity": 1,
    "opted-out-at-round": 1,
    "advertiser": 1,
    "rewards": 1,
    "platform": 1,
    "requirements": 1,
}

```

**Comment by moloch10** [comment]
> Yes, if a JSON has that "animated_url" then we probably should use it, or fail back to "image". 

Sounds good.
