### ISSUE TITLE
Links to Pact Swap don't load second asset

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#163]
Current links are as such:
https://app.pact.fi/swap?pair=ALGO0/ASA+STATS+TOKEN393537671(30)

The second asset does not load up.

It seems like they changed their URL as this loads up correctly:
https://app.pact.fi/swap?pair=ALGO0/ASA+STATS+TOKEN393537671(30,CONST)

The added `,CONST` can be seen when picking any second asset.

**Comment by ipaleka** [comment]
Thanks for this report, their upgrade brought also a solution for reversed swap links (through a dash prefix) and we have implemented them now.

**Comment by moloch10** [comment]
> Thanks for this report, their upgrade brought also a solution for reversed swap links (through a dash prefix) and we have implemented them now.

Yup yup, I saw that as well 😀
