### ISSUE TITLE
Apply for Pera Wallet ASA Verification

### ISSUE THREAD

**Issue by SCN9A** [asastats/channel#20]
Application is [open](https://blog.perawallet.app/pera-wallet-asa-verification-portal-is-open-for-applications-2c01dc548559)

**Comment by ipaleka** [comment]
## Your application has been accepted

Congratulations, your application for Pera Wallet ASA verification for ASA 393537671has been approved, and your Verified status will be live in 15 minutes.

Regards, 
Pera Wallet Team

**Comment by ipaleka** [comment]
ASA verified!

Congratulations, your ASA is now verified. Within 48 hours, your verified badge will show up in Pera Wallet.

**Comment by ipaleka** [comment]
Are there any resources about getting that "Trusted" badge?

**Comment by ipaleka** [comment]
> On Pera Subreddit, [Pera Wallet ASA Verification Portal is Open for Applications!](https://www.reddit.com/r/PeraWallet/comments/ud5u59/pera_wallet_asa_verification_portal_is_open_for/), Mod's response to "How do we start the 'trusted' procedure?" was "Oh, simply you need to be verified first :)"

Also this:

> **Pera will reach out** to select Verified projects to upgrade their ASAs to Trusted tier.
