### ISSUE TITLE
Allow input of address on the portfolio viewer

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#23]
Would be nice if the address on top of the page was in a text box input so it could be changed there without having to go home or changing the URL directly.

**Comment by ipaleka** [comment]
Btw, let me use this opportunity, are you able to change/set labels here in this issue?

**Comment by moloch10** [comment]
> Would you mind explaining the reasoning for a kind of duplicating such behavior as every browser, as you mentioned, have such a text box just an _inch_ above, and you can edit just an address by double-clicking the suffix/address?

While it is simple to change the address in the URL bar on a desktop, it's not part of the application / site. Changing the URL directly seems to go against the usage of a site. If we wanted to see the about page, we're not expected to type it out even though it's easy to do so, we use the interface. On a mobile device, it's even more cumbersome to get the pointer to the right place and delete and paste in the new one.

**Comment by moloch10** [comment]
> Btw, let me use this opportunity, are you able to change/set labels here in this issue?

I was looking for the ability to do this for a few minutes but was unable to find it so I'm going to say no, I can't change or set them. I do however see the labels you set under the labels section but again, they're read only.

**Comment by ipaleka** [comment]
> > Would you mind explaining the reasoning for a kind of duplicating such behavior as every browser, as you mentioned, have such a text box just an _inch_ above, and you can edit just an address by double-clicking the suffix/address?
> 
> While it is simple to change the address in the URL bar on a desktop, it's not part of the application / site. Changing the URL directly seems to go against the usage of a site. If we wanted to see the about page, we're not expected to type it out even though it's easy to do so, we use the interface. On a mobile device, it's even more cumbersome to get the pointer to the right place and delete and paste in the new one.

The alternative is to click the logo and paste an address in the input box there. That's pretty much the same amount of steps if we keep the current header visual as it is now and transform into input box upon clicking the header, as index page's input box has got autofocus property.

Another option is to create a permanent input box out of the header and that would look ugly if you ask me.

We can open [a discussion](https://github.com/asastats/channel/discussions) about this and make a poll afterward.

**Comment by ipaleka** [comment]
> > Btw, let me use this opportunity, are you able to change/set labels here in this issue?
> 
> I was looking for the ability to do this for a few minutes but was unable to find it so I'm going to say no, I can't change or set them. I do however see the labels you set under the labels section but again, they're read only.

Thanks, if there's no a settings icon on the right of the labels then you don't have a permission even if you created this issue. I'm going to check more, my intention has been to add permission for that to DAO group, but still can't find it.

**Comment by ipaleka** [comment]
I've added the members of [DAO](https://github.com/orgs/asastats/teams/dao) and [Community](https://github.com/orgs/asastats/teams/community) teams to "triage" permission, it looks like that can allow you to set the labels. Can you please try when you get some spare time? Thanks!! :)

**Comment by moloch10** [comment]
> I've added the members of [DAO](https://github.com/orgs/asastats/teams/dao) and [Community](https://github.com/orgs/asastats/teams/community) teams to "triage" permission, it looks like that can allow you to set the labels. Can you please try when you get some spare time? Thanks!! :)

Looks good. In addition to the labels, I can now also edit assignees and milestone.

**Comment by ipaleka** [comment]
I'm closing this, if a discussion would be open and if it outcomes with a request then another issue would be created (probably with a link to this one together with a link to the related discussion).
