### ISSUE TITLE
Add chart link for the ALGO too

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#25]
https://discord.com/channels/906917846754418770/915342738201931836/961773636602175508
> I noticed the Algo drop down does not have a chart link.  I go to a chart from another asset to check Algo.  Seems it could have a link in its drop down like the other assets.

> We have an open research card for Live Coin https://www.livecoinwatch.com/price/Algorand-ALGO, we can add them then.

**Comment by ipaleka** [comment]
CoinMarketCap and Live Coin Watch links are added.

**Comment by AlgoRhythMatic** [comment]
Type: [F1]
Recipient: motuwagon (Discord) - 100%
