### ISSUE TITLE
[B2] URL to ARC19 NFT in portfolio view

### ISSUE THREAD

**Issue by SCN9A** [asastats/channel#252]
Clicking on either URLs as well as the NFT thumblenail does not open the image file. This has been replicated for ARC 19 NFTs from different collections (E.g CoffeeBits Bather, Algoanna V2)

### Example below

**CoffeeBits Bather**
<img width="1136" alt="CoffeeBits Bather #3009" src="https://user-images.githubusercontent.com/95645978/192111101-4fec50bc-7b66-4d56-a736-6d98eeeeddf9.png">

First URL: https://ipfs.io/ipfs/bafkreibtuiv3dowmhvb3amdbq5nuzjqt2iui43mr3esgilwa5plltyav6q
<img width="718" alt="First URL" src="https://user-images.githubusercontent.com/95645978/192111108-30f299db-5f67-457f-924f-7c0e32646baa.png">

Second URL: https://template-ipfs//%7Bipfscid:1:raw:reserve:sha2-256%7D
<img width="825" alt="Second URL" src="https://user-images.githubusercontent.com/95645978/192111112-20f6314f-614d-4f1f-b4b5-802449331c75.png">

**MvZ Zombie #2348**
<img width="1144" alt="MvZ Zombie #2348" src="https://user-images.githubusercontent.com/95645978/192111193-7d9cbeb0-751c-46d7-9598-e22b48489bd6.png">

First URL: https://cloudflare-ipfs.com/ipfs/bafkreiblqibseq5wnpdhorytj265qnv5rbvw6b2kxysgkp24lts5k64eky
<img width="1467" alt="First URL" src="https://user-images.githubusercontent.com/95645978/192111240-4718ba34-acb6-462b-abcf-c952badd4501.png">

Second URL: https://template-ipfs//%7Bipfscid:1:raw:reserve:sha2-256%7D#arc3
<img width="724" alt="Second URL" src="https://user-images.githubusercontent.com/95645978/192111248-37702029-1035-46cb-8b77-f583f889ace6.png">

**Comment by ipaleka** [comment]
Thanks for pointing out this! 

We had missed having a discussion about this so the initial setup has been implemented.

**Comment by ipaleka** [comment]
Also metadata was missing from arc19...
