### ISSUE TITLE
Non-lowercase ANS name isn't resolved

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#26]
> https://twitter.com/Emzeed01/status/1519770314485420035

Internal server error was a side-effect.

**Comment by ipaleka** [comment]
It's resolved on our side, and also anssdk is [going to be updated](https://discord.com/channels/906917846754418770/908054330265960478/969333396855750676) by ANS devs.

**Comment by AlgoRhythMatic** [comment]
Type: [B1]
Recipient: @Emzeed01 (Twitter) - 100%
