### ISSUE TITLE
Defly to Defly Staking on Algofi currently not showing on ASA Stats

### ISSUE THREAD

**Issue by marucat27** [asastats/channel#272]
Was showing previously, not sure what happened?  Maybe on Algofi's end?

**Comment by ipaleka** [comment]
> Was showing previously, not sure what happened? Maybe on Algofi's end?

It is definitely on our end as we just resolved another Algofi issue and that cache probably kept the old record. We're about to find out what's wrong with the system that doesn't update Algofi staking program(s).

**Comment by ipaleka** [comment]
Above mentioned issue cache problem was hiding the problem from this issue that has been now revealed in plain sight. :)
