### ISSUE TITLE
[Internal] Add AlgoRai's goBTC and goETH vaults

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#279]
https://medium.com/@algorai.finance/algorai-finance-partners-with-algomint-to-launch-gobtc-goeth-options-vaults-bb847daea5

> Call and Put strategies on goBTC and goETH will be offered and vaults will be open from Friday 14th October 2022.

**Comment by ipaleka** [comment]
These vaults aren't deployed yet.

**Comment by marucat27** [comment]
https://twitter.com/fredestante/status/1585959484085612544

**Comment by ipaleka** [comment]
These vaults aren't deployed yet, we'll open a new issue once when they hit the Mainnet.

**Comment by ipaleka** [comment]
It looks like they are coming in 5-6 days.
