### ISSUE TITLE
Algofi updating is stopped

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#28]
Reddit DM:

- - - - -
Hi

I wanted ask a question about asa stats

I realized it wasn’t reflecting a loan paid in algofi

Should asa stats be reflecting such?  Thanks!!!

- - - - -

[u/Aromatic-Ad3922](https://www.reddit.com/user/Aromatic-Ad3922/) in our [subreddit]( 
https://www.reddit.com/r/asastats/comments/ttsxu0/comment/i6i1537/?utm_source=share&utm_medium=web2x&context=3)
> Is Algofi’s lending and borrowing delayed on asa stats? Thanks

- - - - -

We're on it right now!

**Comment by ipaleka** [comment]
The problem with Algofi updating is fixed and updates run as scheduled, this issue will be closed after confirmation is received from u/Aromatic-Ad3922.

**Comment by AlgoRhythMatic** [comment]
Type: [B1]
Recipient: u/Aromatic-Ad3922 (Reddit) - 100%
