### ISSUE TITLE
Trust/Algo new farm on humble

### ISSUE THREAD

**Issue by BartleDooDerp** [asastats/channel#287]
Not Tracked
https://algoexplorer.io/asset/577176220

**Comment by ipaleka** [comment]
The issue exists and TRUST farm has been deployed https://github.com/asastats/channel/issues/286.

I'ma about to close this as I guess this is just a late respond as our testing account shows the farm:
![trust](https://user-images.githubusercontent.com/49662536/196052336-68338fc7-5556-46cd-893e-ed5c9207b307.png)
