### ISSUE TITLE
Update ASA Stats on Algorand Ecosystem Directory

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#29]
https://github.com/asastats/static-pages/issues/5#issuecomment-1113260975  
> I suggest we update ASA Stats [project information](https://ecosystem.algorand.com/project/asa-stats) on Algorand Ecosystem Directory. 

> The above information are suitable. Mission, goals and value proposition sections may be enough.

**Comment by ipaleka** [comment]
> One line simple description of project

ASA Stats aims to have accurate and up-to-date price information for every ASA and NFT that has ever been sold on Algorand.

> Detailed overview of the project

ASA Stats is a portfolio tracking website that enables users to evaluate the current balance of all assets associated with their wallet address on the Algorand blockchain. Every asset presented is accompanied by a link to a page source where a user can verify the accuracy of the information.

ASA Stats aims to become the primary source of price information on the Algorand blockchain for traders and software companies. It will bring every price available from any Algorand DEX or AMM, as well as from any NFT marketplace. In order to remain accessible to a broad audience, ASA Stats will continue to provide free services for average, non-professional use.

The primary goal for ASA Stats is to provide the best possible user experience while remaining a leader in the Algorand portfolio tracker category. To support the pursuit of this goal, the plan is to establish a decentralized autonomous organization (DAO).

In the current pre-DAO phase, ASA Stats is already operating in a decentralized way by streamlining a process for the community to deliver their requests on a daily basis. Due to the open nature of the community channels, other users are then able to provide additional feedback and show support or dissent, which can help to understand what features are most important.

> Overview of how Algorand is being used

ASA Stats will implement every publicly available SDK/API of all major DEX solutions on the Algorand blockchain as soon as an SDK/API is available. Every other dApp on Algorand that locks users' ASA or ALGO will be researched and implemented.

**Comment by ipaleka** [comment]
It seems that links are not allowed in the body of those sections.

Also, not sure how they parse that links field as last time placing them in each line didn't work, so right now only one entry (https://www.asastats.com/whitepaper.pdf) is there.

**Comment by SCN9A** [comment]
### One line simple description of project
The mission of ASA Stats is to become the primary source of price information for every ASA on the Algorand blockchain for traders and software companies. ASA Stats will continue to provide free services for average, non-professional use.

### Detailed overview of the project

ASA & NFT Valuation consist of three dynamic substrate: A: SDK implementation of all major DEX or AMM, as well as from any NFT marketplace on the Algorand blockchain, B: Selling Price Optimisation to bring maximum value for user's asset by calculating the optimal amounts that should be sold on each of the AMMs or DEXes, C: Pricing Algorithms for NFTs that have never been sold.

ASA Stats API and Feature-Driven Development are aimed at building ready-to-use software tools for service providers and software companies, creating advanced web widgets for use in portfolio view and building databases and other bidirectional data streaming.

### Overview of how Algorand is being used

ASA Stats Portfolio Tracker evaluates and presents the current balance for any wallet address on the Algorand blockchain. ASA Stats Token is a utility token meant to be used for purchasing various professional services from ASA Stats. One of the primary goals and a measure of success for ASA Stats project is the establishment of Decentralized Autonomous Organization (DAO) that will take over after the initial phase of the project is successfully completed.

**Comment by SCN9A** [comment]
### One line simple description of project
The mission of ASA Stats is to become the primary source of price information for every ASA on the Algorand blockchain for traders and software companies. ASA Stats will continue to provide free services for average, non-professional use.

### Detailed overview of the project

ASA & NFT Valuation consist of three dynamic substrate: A: SDK implementation of all major DEX or AMM, as well as from any NFT marketplace on the Algorand blockchain, B: Selling Price Optimisation to bring maximum value for user's asset by calculating the optimal amounts that should be sold on each of the AMMs or DEXes, C: Pricing Algorithms for NFTs that have never been sold.

ASA Stats API and Feature-Driven Development are aimed at building ready-to-use software tools for service providers and software companies, creating advanced web widgets for use in portfolio view and building databases and other bidirectional data streaming.

### Overview of how Algorand is being used

ASA Stats Portfolio Tracker evaluates and presents the current balance for any wallet address on the Algorand blockchain. ASA Stats Token is a utility token meant to be used for purchasing various professional services from ASA Stats. One of the primary goals and a measure of success for ASA Stats project is the establishment of Decentralized Autonomous Organization (DAO) that will take over after the initial phase of the project is successfully completed.

**Comment by SCN9A** [comment]
> It seems that links are not allowed in the body of those sections.
> 
> Also, not sure how they parse that links field as last time placing them in each line didn't work, so right now only one entry (https://www.asastats.com/whitepaper.pdf) is there.

@ipaleka I suggest we replace the current link (White paper) with a link to [About page](https://www.asastats.com/about/) or [Explainer Video](https://www.youtube.com/watch?v=M8_dWMNWmCo).

**Comment by SCN9A** [comment]
> It seems that links are not allowed in the body of those sections.
> 
> Also, not sure how they parse that links field as last time placing them in each line didn't work, so right now only one entry (https://www.asastats.com/whitepaper.pdf) is there.

@ipaleka I suggest we replace the current link (White paper) with a link to [About page](https://www.asastats.com/about/) or [Explainer Video](https://www.youtube.com/watch?v=M8_dWMNWmCo).

**Comment by ipaleka** [comment]
> 



> > It seems that links are not allowed in the body of those sections.
> > Also, not sure how they parse that links field as last time placing them in each line didn't work, so right now only one entry (https://www.asastats.com/whitepaper.pdf) is there.
> 
> @ipaleka I suggest we replace the current link (White paper) with a link to [About page](https://www.asastats.com/about/) or [Explainer Video](https://www.youtube.com/watch?v=M8_dWMNWmCo).

That field title is: "White Paper, Litepaper, other documentation URL/links". I mean, it does mention links, but there's also link to website where the About page is linked in the header and the footer, so if we have to use one link, I'd be rather with the whitepaper.

Nevertheless, the main question and problem-solver is to find out how we should group those links so we can have more than one.

**Comment by ipaleka** [comment]
> ### Overview of how Algorand is being used
> 
> ASA Stats Portfolio Tracker evaluates and presents the current balance for any wallet address on the Algorand blockchain. ASA Stats Token is a utility token meant to be used for purchasing various professional services from ASA Stats. One of the primary goals and a measure of success for ASA Stats project is the establishment of Decentralized Autonomous Organization (DAO) that will take over after the initial phase of the project is successfully completed.

This one doesn't sound right to me. For example, this is the current text:

>ASA Stats will implement every publicly available SDK/API of all major DEX solutions on the Algorand blockchain as soon as an SDK/API is available. Every other dApp on Algorand that locks users' ASA or ALGO will be researched and implemented.

It is more precise in the regard of how the section is entitled afaic.

**Comment by SCN9A** [comment]
> Nevertheless, the main question and problem-solver is to find out how we should group those links so we can have more than one.

https://linktr.ee/ has been used by some NFT projects on Twitter and it may be worth a try. Here are some [templates](https://linktr.ee/s/templates/sell). The free plan should be enough.

**Comment by SCN9A** [comment]
> Nevertheless, the main question and problem-solver is to find out how we should group those links so we can have more than one.

https://linktr.ee/ has been used by some NFT projects on Twitter and it may be worth a try. Here are some [templates](https://linktr.ee/s/templates/sell). The free plan should be enough.

**Comment by ipaleka** [comment]
> > Nevertheless, the main question and problem-solver is to find out how we should group those links so we can have more than one.
> 
> https://linktr.ee/ has been used by some NFT projects on Twitter and it may be worth a try. Here are some [templates](https://linktr.ee/s/templates/sell). The free plan should be enough.

Sorry, I didn't explain well what I mean. There's a textarea input box for the purpose and people have used it to list multiple links nit, separated by space or so, but the portal doesn't parse those links at all, it's a bug on their side tho.

For example [Choice Coin's entry](https://ecosystem.algorand.com/project/choice-coin) is wrong, while the others have noticed that bug and they just comprehend that "Other resources" as singular and they add just whitepaper or so (like https://ecosystem.algorand.com/project/kaafila).

I really don't want to link to a third-party provider, we should stick to what other do, and that happens to be a link to whitepaper.

I mean, until they fix that and correctly parse those entries from the textarea input box.

**Comment by ipaleka** [comment]
> 



> ### One line simple description of project
> 
> The mission of ASA Stats is to become the primary source of price information for every ASA on the Algorand blockchain for traders and software companies. ASA Stats will continue to provide free services for average, non-professional use.
> ### Detailed overview of the project
> 
> ASA & NFT Valuation consist of three dynamic substrate: A: SDK implementation of all major DEX or AMM, as well as from any NFT marketplace on the Algorand blockchain, B: Selling Price Optimisation to bring maximum value for user's asset by calculating the optimal amounts that should be sold on each of the AMMs or DEXes, C: Pricing Algorithms for NFTs that have never been sold.
> 
> ASA Stats API and Feature-Driven Development are aimed at building ready-to-use software tools for service providers and software companies, creating advanced web widgets for use in portfolio view and building databases and other bidirectional data streaming.
> ### Overview of how Algorand is being used
> 
> ASA Stats Portfolio Tracker evaluates and presents the current balance for any wallet address on the Algorand blockchain. ASA Stats Token is a utility token meant to be used for purchasing various professional services from ASA Stats. One of the primary goals and a measure of success for ASA Stats project is the establishment of Decentralized Autonomous Organization (DAO) that will take over after the initial phase of the project is successfully completed.

I did update the page with this suggestion.

**Comment by ipaleka** [comment]
I'm closing this, no update from them for a month...
