### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by marucat27** [asastats/channel#292]
Receiving Internal Server Error on site.

**Comment by ipaleka** [comment]
All the interval server errors are logged and we check for them regularly. This one was reported 9 hours ago while our last one was recorded 18 hours ago and it is connected with the last phase of the Node update.

Did yo actually report 9 hours after the error happened?

**Comment by marucat27** [comment]
Acknowledged.  Issue has been resolved.  Thank you.

**Comment by ipaleka** [comment]
Basically, every internal server error is tracked and it's prioritized even more than issues here. This last series of such errors were caused directly by [the Algorand Node issue](https://github.com/algorand/go-algorand/issues/4661) or as a consequence of attempts to bypass it.
