### ISSUE TITLE
ALCH (AlcheCoin 310014962) is now "Not evaluated"

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#30]
https://discord.com/channels/906917846754418770/908054330265960478/969612534934044774  
> ALCH (AlcheCoin 310014962) is now "Not evaluated" but it used to be. Not sure if it's just for my ALCH I've got in ALCH-YLDY LP or not.

**Comment by AlgoRhythMatic** [comment]
Type: [B1]
Recipient: DragMZ (Discord) - 100%
