### ISSUE TITLE
Defly algofi staking link redirects to older non working site

### ISSUE THREAD

**Issue by marucat27** [asastats/channel#300]
Edit by ipaleka: moloch10 [F1]
- - - - -

When clicking on the Defly algofi staking link, this page shows up.  ![image](https://user-images.githubusercontent.com/109246416/197241421-54872e39-06d3-4ab5-b5ed-cc5d379a4241.jpeg)

**Comment by kerrilija** [comment]
This was already reported by moloch10 in #bug-reports in our Discord server.

https://discord.com/channels/906917846754418770/908054330265960478/1032080469874982912
