### ISSUE TITLE
NFTs aren't displaying preview and clicking their link sometimes displays the image, sometimes times out.

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#307]
682361621 - Ducky Card
682359506 - Gold Ducky Card
796490640 - Shitty Kitty Treats

Not sure if it matters but all three are multi-mints.

**Comment by ipaleka** [comment]
Those three NFTs are added through their creator addresses (the first two have got the same creator). That implies that the rest of the related creator's NFTs are added too if they were missing (if they are valid and reachable in IPFS gateways, of course).
