### ISSUE TITLE
Research and implement new NFT market: https://exa.market

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#336]

**Comment by ipaleka** [comment]
Great product, indeed

**Comment by moloch10** [comment]
From one of their discord admins @Ella | EXA just a few hours ago:

> API data will be available shortly.

https://discord.com/channels/870460271817289768/1014471169279275118/1039935372022521906

**Comment by ipaleka** [comment]
> From one of their discord admins @ella | EXA just a few hours ago:
> 
> > API data will be available shortly.
> 
> https://discord.com/channels/870460271817289768/1014471169279275118/1039935372022521906

API is always a last resort for us, when we can't gather data from blockchain, respectively when we deal with web shops like RandGallery. Fortunately, this has been a pure onchain project.

**Comment by moloch10** [comment]
I recently made a purchase from this market and checked that asset's page on nftexplorer.app. Even though they aren't pulling listings from the market, I see that my purchase is correctly listed in the sales history. 

Would the txn or asset ID be useful to you?

**Comment by ipaleka** [comment]
Deployment goes on Monday.
