### ISSUE TITLE
Cometa Farm for Grow/algo

### ISSUE THREAD

**Issue by BartleDooDerp** [asastats/channel#352]
thanks.
https://algoexplorer.io/application/953446671

**Comment by BartleDooDerp** [comment]
also
https://algoexplorer.io/application/953426386

**Comment by ipaleka** [comment]
By UncleDooom in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1044484129145761915) — Today at 6:27 AM

> New GROW (Polymeta) farms on Cometa  

> Under Farm and Stake both

**Comment by ipaleka** [comment]
Usually, only the first reporter gets rewards (UncleDooom was first), but in this case we reward creating an issue as a task.

This practice will stay for the future, I suppose.
