### ISSUE TITLE
[B2] Miscalculated FLP amount for FXDX exchange

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#355]
By Reems in kerrilija's Discord DM:

> Hey there, I wanted to let you know that the ASAStats page is miscalculating FLP for the FXDX exchange 🙂 It says I have 783 when I have 435

**Comment by ipaleka** [comment]
FXDX changes that coefficient based on internal calculations and finance flow, we are in contact with our governor 0xZer0 from FXDX, but as of now there is no API endpoint or onchain information we can fetch in order to retrieve it, we simply have to count on user's reports after it changes.

Therefore, B1 for reporter Reems, B1 for kerrilija if he manages to get a public Algorand address from Reems.

**Comment by ipaleka** [comment]
P.S. 0xZer0 has provided an endpoint for this information, so automatically retrieving the coefficient will be implemented in the following days. :)

**Comment by AlgoRhythMatic** [comment]
> B1 for kerrilija if he manages to get a public Algorand address from Reems.
@kerrilija confirmed that that Reems address has now been provided to @ipaleka.
