### ISSUE TITLE
Research Vestige vaults locker

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#367]
By Miki in Telegram DM:

> Would Vestige.fi vaults be implemented in ASA Stats?

**Comment by ipaleka** [comment]
Alpha version has been deployed without any timestamp presentation (should be available in BETA).

Also it doesn't cover LP tokens: https://github.com/asastats/channel/issues/381

**Comment by AlgoRhythMatic** [comment]
@ipaleka re: Miki in Telegram DM - are you able to acquire this users wallet address?  Is there some notation I should use for a Telegram user in the standard output formatting?

**Comment by ipaleka** [comment]
> @ipaleka re: Miki in Telegram DM - are you able to acquire this users wallet address? 

Yes, I'll reach him with a request for an address.

> Is there some notation I should use for a Telegram user in the standard output formatting?

Hm, dunno, I guess you can prefix it with t@...
`
