### ISSUE TITLE
Research and prepare for the Tinyman v2 deployment 1/5/23

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#375]
By motuwagon in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1054188003989389362):

> Anyone know when tinyman v2 is launched? Will LP pool need to be withdrawn and re established on v2?

- - - - -

https://twitter.com/tinymanorg/status/1595787206462947328

**Comment by RanTask** [comment]
Guys, Tinyman v2 is live and I migrated my liquidity to v2 today. We should migrate everything asap.

**Comment by ipaleka** [comment]
> Guys, Tinyman v2 is live and I migrated my liquidity to v2 today. We should migrate everything asap.

https://github.com/asastats/channel/discussions/328#discussioncomment-4603114
