### ISSUE TITLE
Vestige Vault LP tokens locking

### ISSUE THREAD

**Issue by BartleDooDerp** [asastats/channel#381]
Hello,

Please update this so it tracked.

Thank you very much and Happy Holidays!

https://algoexplorer.io/application/985646673

**Comment by ipaleka** [comment]
Happy Holidays to you too!

Vestige Vaults research as requested here https://github.com/asastats/channel/issues/367 is done, and development and deployment are expected the following week.

**Comment by ipaleka** [comment]
I've reopened this one as it brings a feature that isn't implemented in the just-released Alpha version. Alpha doesn't cover LP tokens like in this issue's app.
