### ISSUE TITLE
Add note about server 500 errors to the FAQ

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#39]
Another fine task for a community member.

https://github.com/asastats/static-pages/tree/main/faq

So, basically, when a user encounters a server 500 error they don't need to report them asap as they are checked on a daily basis, but they can do that by simply reporting in our community channels or here that one just happened, and that way enforce a quick check.

**Comment by SCN9A** [comment]
I do not think this is a FAQ. ASA Stats server errors are isolated incidents which are being dealt with swiftly. During the past months of using ASA Stats website, I can't remember having server errors. 

Including the question in FAG may give the impression of instability, frequent server downtime.

**Comment by SCN9A** [comment]
I do not think this is a FAQ. ASA Stats server errors are isolated incidents which are being dealt with swiftly. During the past months of using ASA Stats website, I can't remember having server errors. 

Including the question in FAG may give the impression of instability, frequent server downtime.

**Comment by ipaleka** [comment]
> I do not think this is a FAQ. ASA Stats server errors are isolated incidents which are being dealt with swiftly. During the past months of using ASA Stats website, I can't remember having server errors.
> 
> Including the question in FAG may give the impression of instability, frequent server downtime.

Very well explained, thank you!

**Comment by ipaleka** [comment]
Server error 500 from now on carries a note that the development team is informed of the error.
