### ISSUE TITLE
Not a bug... New Farms up on humble for Vestige and Defly

### ISSUE THREAD

**Issue by BartleDooDerp** [asastats/channel#394]
https://app.humble.sh/farm?id=997488528

https://app.humble.sh/farm?id=985349136

Thank You sir.

Bug description:

**Comment by ipaleka** [comment]
And ALGO-BANANA.

**Comment by ipaleka** [comment]
ALGO-BANANA farm too.

**Comment by kerrilija** [comment]
@BartleDooDerp 

For this particular issue we would usually use the "Feature request" template. We've created templates for Issues yesterday, if you have a better idea how we could make them more intuitive / more precise, please suggest. Cheers! :)
