### ISSUE TITLE
Add to FAQ reasoning for not having historic data implemented by ourselves

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#40]
The following comment should be proofread and presented in our FAQ: https://github.com/asastats/static-pages/tree/main/faq

- - - - -

https://www.reddit.com/r/asastats/comments/t1e3i6/comment/hyfiv5d/?utm_source=share&utm_medium=web2x&context=3
> That would be extremely useful and wouldn’t seem too difficult to implement  

The goal for ASA Stats in pre-DAO phase is to create a solid ground for the DAO from the business perspective as ASA Stats is primarily a business entity.

Therefore, our goal isn't just to satisfy our users' needs - even that is indeed a primary and everlasting goal - we want to involve other parties, notably developers and other software companies, to use our future API and then we'll use and present their aggregate data back to our users in the form of user widgets.

That being said, we want to create a competition of possibilities for our users rather than just provide a piece of needed information that in theory can prevent our growth.

**Comment by SCN9A** [comment]
@ipaleka A matter of fact this question was included in the [community draft document](https://docs.google.com/document/d/1hxf9bxzJnklJ5M6oBEdCQGRx5kN6d3SxA06AO8sMfCo/edit#) on Google Docs.

> **Will you one day show (fill in the blank)?** ....... The one we get the most requests about is viewing historical token prices or price changes. We currently have no plans to implement this directly on ASA Stats. However, once our API is developed we will be creating partnerships with other developers. Our users will then be able to pick and choose which widgets (created by our partners) they want to display- we hope things like trading gains and losses will be one of those widgets. We have no intention to execute trades on our platform.

I suggest the following iteration, as ASA Stats sponsoring developers is an option, in addition to creating partnerships.

### Why historical data of ASA price changes are not implemented by ASA Stats?
The goal for ASA Stats in pre-DAO phase is to create a solid ground for the DAO from the business perspective. We currently have no plans to implement historical data of ASA price changes directly on ASA Stats. However, ASA Stats will be encouraging partnerships and sponsoring developers once our API is ready to create advanced web widgets for use in the portfolio view (e.g. ASA Price change Widget). We have no intention to execute trades on our platform.


The final version should be Added to "Service Users" section in FAQ [Page](https://www.asastats.com/faq/).

**Comment by SCN9A** [comment]
@ipaleka A matter of fact this question was included in the [community draft document](https://docs.google.com/document/d/1hxf9bxzJnklJ5M6oBEdCQGRx5kN6d3SxA06AO8sMfCo/edit#) on Google Docs.

> **Will you one day show (fill in the blank)?** ....... The one we get the most requests about is viewing historical token prices or price changes. We currently have no plans to implement this directly on ASA Stats. However, once our API is developed we will be creating partnerships with other developers. Our users will then be able to pick and choose which widgets (created by our partners) they want to display- we hope things like trading gains and losses will be one of those widgets. We have no intention to execute trades on our platform.

I suggest the following iteration, as ASA Stats sponsoring developers is an option, in addition to creating partnerships.

### Why historical data of ASA price changes are not implemented by ASA Stats?
The goal for ASA Stats in pre-DAO phase is to create a solid ground for the DAO from the business perspective. We currently have no plans to implement historical data of ASA price changes directly on ASA Stats. However, ASA Stats will be encouraging partnerships and sponsoring developers once our API is ready to create advanced web widgets for use in the portfolio view (e.g. ASA Price change Widget). We have no intention to execute trades on our platform.


The final version should be Added to "Service Users" section in FAQ [Page](https://www.asastats.com/faq/).

**Comment by ipaleka** [comment]
> @ipaleka A matter of fact this question was included in the [community draft document](https://docs.google.com/document/d/1hxf9bxzJnklJ5M6oBEdCQGRx5kN6d3SxA06AO8sMfCo/edit#) on Google Docs.
> 
> > **Will you one day show (fill in the blank)?** ....... The one we get the most requests about is viewing historical token prices or price changes. We currently have no plans to implement this directly on ASA Stats. However, once our API is developed we will be creating partnerships with other developers. Our users will then be able to pick and choose which widgets (created by our partners) they want to display- we hope things like trading gains and losses will be one of those widgets. We have no intention to execute trades on our platform.
> 
> I suggest the following iteration, as ASA Stats sponsoring developers is an option, in addition to creating partnerships.
> ### Why historical data of ASA price changes are not implemented by ASA Stats?
> 
> The goal for ASA Stats in pre-DAO phase is to create a solid ground for the DAO from the business perspective. We currently have no plans to implement historical data of ASA price changes directly on ASA Stats. However, ASA Stats will be encouraging partnerships and sponsoring developers once our API is ready to create advanced web widgets for use in the portfolio view (e.g. ASA Price change Widget). We have no intention to execute trades on our platform.
> 
> The final version should be Added to "Service Users" section in FAQ [Page](https://www.asastats.com/faq/).

Can you please involve more of the reasoning from the original comment here as that's the real reason...

There are no hidden thoughts in ASA Stats and the real and pretty much the only reason **why we don't implement** historic data (the question= is because we want people to use our API instead.

**Comment by ipaleka** [comment]
https://github.com/asastats/channel/discussions/42

**Comment by SCN9A** [comment]
> Can you please involve more of the reasoning from the original comment here as that's the real reason...
> 
> 
> 
> There are no hidden thoughts in ASA Stats and the real and pretty much the only reason **why we don't implement** historic data (the question) is because we want to encourage people to use our API, among other reasons, because of that.
> 
> 
> 
> We are a business, and we don't want to create obstacles for our business.

I am afraid we are assuming service users are developers which may not be precise. 

Users’ objective is to get the feature available. Knowing that we want others to use out API doesn’t add to the objective. 

I will add more reasoning if you still find it necessary

**Comment by ipaleka** [comment]
> Users’ objective is to get the feature available. Knowing that we want others to use out API doesn’t add to the objective.

I sometimes make articles to explain what a native English speaker can do in a sentence! :)

We want that third-party developer uses the fact that we don't have those types of data directly in ASA Stats in a way that they either fetch our data and send it back in an aggregate form to asastats.com in a form of the user widgets, or to develop their custom solutions from our data and offer such historic data.

> I will add more reasoning if you still find it necessary

Yes, please continue in our discussion https://github.com/asastats/channel/discussions/42 that should outcome with the proper answer to that question.

**Comment by ipaleka** [comment]
Deployed.
