### ISSUE TITLE
Shown amount for the Governance Reward is incorrect

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#400]
Bug description:

Current:
![image](https://user-images.githubusercontent.com/97535612/211082801-a698056e-d683-4e02-b903-01abb4ccbf1b.png)

Actual received:
![image](https://user-images.githubusercontent.com/97535612/211083150-bbbefb84-bc3c-4da5-9d90-b2d8a3565936.png)

Algofi shows this for the payout:
![image](https://user-images.githubusercontent.com/97535612/211083285-f4facbdc-e597-4caa-8458-54bc9f60b5e8.png)
![image](https://user-images.githubusercontent.com/97535612/211083626-eba0fc93-40db-450c-b00c-0181e235dd86.png)

There's an extra payout because these ALGO are in DeFi.

**Comment by ipaleka** [comment]
This is directly connected to this: https://github.com/asastats/channel/issues/293

We fetch only official Algorand governance rewards for now.
