### ISSUE TITLE
[F1 + IC] Add Cometa's COSG-COSG staking program

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#411]
By rockiitp on [Reddit](https://www.reddit.com/r/asastats/comments/108vzyu/new_cosg_staking_on_cometa/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button):

> Just wanted to flag the new cosg stake on cometa-appears asastats isn't reflecting it.  Coins are locked for 30 days-hoping that won't prevent picking it up.

Feature link:

https://app.cometa.farm/stake

Application ID:

1007157345

**Comment by ipaleka** [comment]
+ ALGO ALCH, META and USDC farms.
