### ISSUE TITLE
[B2] NFTs listed on algoxnft.com do not show up sometimes

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#424]
Bug description:

After some testing here's what I found:

If an NFT is the last of a collection in one's wallet and it's listed on axn, it will NOT show up under Stats. However, if there is at least one other from the collection, then it does properly show with the correct price. I listed and unlisted several different collections to verify that it wasn't specific.
Also, I currently have some other listings on rand and exa that are the last of their collections and they do show up on Stats correctly.

**Comment by moloch10** [comment]
The same last of a collection NFTs that were listed on AxN that didn't show up last week are now showing up correctly.
Something else is I got two from a newly minted set. One is listed on AxN, the other not. Stats shows only one from the collection, the one not listed.  AlgoRaccoon is the newly minted collection.

**Comment by ipaleka** [comment]
Does this relate to not being listed under the correct collection?

Collections are updated in irregular intervals, approximately once a day or so. A newly minted NFT therefore will end up under ABCDE..FGHIJ "collection", creator's address.

**Comment by moloch10** [comment]
When I put this ticket in, the name of the collection for AlgoRaccoon was already known because it was listed as such. The second one which was on AxN was not under the name nor was it listed as its own record with ABCDE.... as the name.
Currently, both for AlgoRaccoon appear correctly.

**Comment by ipaleka** [comment]
> Totally understand. I'll try again with AxN, I'll list "the last" of one and see what happens. Will report back

Thank you so much for this!!

Meanwhile, can you please write the name of the collection from the initial comment here ("The same last of a collection NFTs that were listed on AxN that didn't show up last week are now showing up correctly")?

**Comment by moloch10** [comment]
Ok, this appears to be resolved? I know there were issues with AxN showing the right info at times, maybe this got resolved when those other things did as well?

Just now I listed the last "Ball Head Alien Bug" and that's looking good. 

From the initial one, I tested a few but remember only one, "Algo Girls."

**Comment by ipaleka** [comment]
> Ok, this appears to be resolved? I know there were issues with AxN showing the right info at times, maybe this got resolved when those other things did as well?

It might be, but I simply can't confirm 100%. A fix for [the bug](https://github.com/asastats/channel/issues/454) q2ev reported was a big issue and the process changed with the fix.

**Comment by moloch10** [comment]
> > From the initial one, I tested a few but remember only one, "Algo Girls."
> 
> I'm afraid I'd need a collection name from an NFT that is still in your account...

Damn, maybe "FUGU" or "Mad Bears"

**Comment by ipaleka** [comment]
> Damn, maybe "FUGU" or "Mad Bears"

Can't confirm, but nvm, I'm going to close this as resolved bY the same fix as for the bug q2ev reported.

Thank you for your time and effort! :)
