### ISSUE TITLE
Research and implement xBacked vaults

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#426]
By *DK+-x* in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1064897750862409749):

> xBacked just goes to mainnet, might want to research about it

Link:

https://www.xbacked.io/

**Comment by ipaleka** [comment]
I believe that comes down to adding 760037151 icons to https://github.com/tinymanorg/asa-list ?

**Comment by ipaleka** [comment]
> ~I believe that comes down to adding 760037151 icons to https://github.com/tinymanorg/asa-list ?~

Actually, there's a vault functionality on website.

**Comment by ipaleka** [comment]
Related discussion at https://github.com/asastats/channel/discussions/446.
