### ISSUE TITLE
Cache sync service has been stuck

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#427]
By xy through kerrilija in Discord DM:

> OPUL value in account is wrong

**Comment by AlgoRhythMatic** [comment]
Is xy a known user on some platform?  Or should kerrilija get full credit here?

**Comment by ipaleka** [comment]
> Is xy a known user on some platform? Or should kerrilija get full credit here?

Sorry for the confusion I did with that, please just set the reward to @kerrilija . Tnx!

**Comment by AlgoRhythMatic** [comment]
No worries at all!  Just want to ensure all recipients get correct rewards!
