### ISSUE TITLE
Research Algoneer Metabet 

### ISSUE THREAD

**Issue by SCN9A** [asastats/channel#43]
https://discord.com/channels/906917846754418770/908054304332603402/970391470811017316

> SCN9A: [Algoneer metabet](https://metabet-agnr.herokuapp.com/.) is on main net. Is it feasible to track bet-tokens sent to the either teams? if yes, I will open a feature request on Github

> ipaleka: The rule of thumb is that if a token is under ownership of some account and it is being locked under some other account on Algorand blockchain then we should research and implement such a dApp. Is that the case here?

> SCN9A: I think this case is different. basically one account send (bet) Algo only. It is sent to the team a contestant bet on. then reward is calculated as "The losing side's account is liquidated, platform fees taken from losing side (2%) and the remaining winnings are distributed based on bet amount to the winning participants." [Info](https://metabet-agnr.herokuapp.com/info/).

> DragMZ: I think this qualifies for a research because you lock your ALGO by sending it to one of the addresses so your ALGO is still there until it gets send back or liquidated. Kind of SMILE staking (?).

> ipaleka: Yes, I agree - if funds are still user's then our job is to show them.

**Comment by ipaleka** [comment]
by SCN9A in Discord:  
> I suggest we link information on Github on how to conduct project research? to Code section on channel  https://github.com/asastats/channel.

Well, the thing is that there are too many cases and principles. The best approach should be to discuss. Now when we have got a central point for discussion in a public space, I strongly suggest that we use this issue for discussion.

So, first of all, somebody should confirm what DragMZ said and create robust information from that.

So, the process is that you send your ALGO (only ALGO?) to an escrow (a single one?) and after the *thing* (contest?, game?) is over your funds are returned (automatically or you have to claim them?) or liquidated (all of them?).

So, that's the first step of the research.

**Comment by dragmz** [comment]
Here are example accounts for Villarreal vs Liverpool (https://metabet-agnr.herokuapp.com/event_pages/E8):

- Winner (Liverpool; A) - https://algoexplorer.io/address/PU7TCPPB2YCCAHRXSA2QALYNFOFR4GWNIF4GQAY3JPGLNUISH3COQGSUUA
- Loser (Villarreal; B) - https://algoexplorer.io/address/6DRSLZCHPHPSBEGZRW2T2UL7CWAP2TZA45XWYQS5ZTWI7PNX4VHVBZSEKQ

B has transferred its balance to A after the event has concluded and then the rewards have been sent to the winners.

Here's what might work here:
- ASA Stats monitors (A, B) pairs (the pairs have to either be added manually or scraped)
- Transfers incoming to any of A or B should be logged as locked ALGO (there's an extra condition though that the transfer has to be made before the game started or the funds are lost - "All bets are irreversible any bet sent after the deadline may not be refunded.")
- A transfer from A -> B or B -> A resets all the locked ALGO (it's no longer displayed on ASA Stats; any rewards will be already included in the ALGO balance)

**Comment by ipaleka** [comment]
>     * ASA Stats monitors (A, B) pairs (the pairs have to either be added manually or scraped)

Ti looks like [this account](https://algoexplorer.io/address/XXPLB2IYZ2JVRLY7QAZQ6RN74TBPATDT7QARZD2US2KYJSTJU4JEGOEEHU) sends 0.1 ALGO with a note `www.algoneer.net|||METABET`

>     * Transfers incoming to any of A or B should be logged as locked ALGO (there's an extra condition though that the transfer has to be made before the game started or the funds are lost - "All bets are irreversible any bet sent after the deadline may not be refunded.")

I guess we can be good without even tracking that (it would be ridiculously hard without smart contracts) as they will be seen the same as game losers from our perspective. Their funds are locked just like funds from the others and finally they are either lost for good or refunded back (*may not be refunded*),
*.

**Comment by ipaleka** [comment]
We had been adjusting in the past, we're going to do the same in the future too. :)

If an issue directly expects a discussion about its topic, then a Channel discussion should be created instead of an issue - an issue should then be created after that discussion outcomes with a solution or a path to it.

So, this discussion is moved here: https://github.com/asastats/channel/discussions/59

**Comment by ipaleka** [comment]
The original app is no longer available, so we'll wait for a new version.
