### ISSUE TITLE
Odd weight for Algo Leagues NFTs in the chart a.k.a. For non-ALGO purchases convert NFT price record to ALGO

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#432]
By motuwagon in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1066544415335784458):

>  Has this been reported.  Nft pie  is giving odd weight to my algo leagues.  I have 8  algo leagues total.  I have other nft collections with more nfts at higher values.

**Comment by ipaleka** [comment]
At first, it looks like total supply affects this.

**Comment by ipaleka** [comment]
> At first, it looks like total supply affects this.

Nope, the problem is that the engine uses a purchase record from AlgoGems like it was in ALGO, while the actual currency was AlgoLeagues Coin.

**Comment by moloch10** [comment]
> > At first, it looks like total supply affects this.
> 
> Nope, the problem is that the engine uses a purchase record from AlgoGems like it was in ALGO, while the actual currency was AlgoLeagues Coin.

My collection is of course also pushed to the top; awesome that you found the problem.
