### ISSUE TITLE
[B1+D1] Mobile app renders some NFT thumbnails incorrectly

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#438]
Bug description:

The thumbnail preview for rectangular NFTs is distorted.

Here's a sample of Octorand:
![image](https://user-images.githubusercontent.com/97535612/214088273-ea22e564-525d-417b-ba62-707f50d1a794.png)

Also noticeable for some NFTs in Algo Leagues: [470160671](https://www.nftexplorer.app/asset/470160671), [470157166](https://www.nftexplorer.app/asset/470157166), & [470153662](https://www.nftexplorer.app/asset/470153662)

**Comment by kerrilija** [comment]
Fixed and awaiting deployment.
