### ISSUE TITLE
Research and find conditions to apply for Tinyman farming program

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#442]
By sensorium in [Dioscord](https://discord.com/channels/906917846754418770/914540797054025788/1068145290693050389):

For @Sensoriumx : as you pointed at Tinyman farming program, would you and others be able to find out what are the conditions or at least find a contact whom we may reach and ask about? As a replacement for our in-hosue incentive program.
Their farming programs imply tokens are not leaving accounts and that's what our users have used to.

- - - - -
@ipaleka Conditions for getting approved into tinyman farms? I can try to contact the developers, already talked to them before.

**Comment by Sensoriumx** [comment]
Update on this:

So far I've managed to contact one for the Tinyman telegram mods C-nia. I believe she joined ASASTATS discord server recently. The contacts on Tinyman's tg group we should reach out to regarding farming programs are: @oneoftinnies and @a13432r . So far no luck getting response from them but I believe C-nia already escalated my question to them for a faster response.
One of the requirements for getting into their farming programs include being an essential project on Algorand, which may include having a higher TVL (TVL projects like Cosmic Champs and Headline have currently).

**Comment by ipaleka** [comment]
> which may include having a higher TVL

I guess the research and this part conclude the issue.

**Comment by Sensoriumx** [comment]
Getting no response from @oneoftinies neither on Telegram or Discord. Kinda hard to reach them

**Comment by ipaleka** [comment]
> Getting no response from @oneoftinies neither on Telegram or Discord. Kinda hard to reach them

Well, that adds up to the conclusion and reasoning to close this issue. Thank you! :)
