### ISSUE TITLE
Outdated AlgoDEX amounts are shown

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#46]
https://discord.com/channels/906917846754418770/908054330265960478/970678134577983568
> My ASASTATS balance on asastats.com seems to be outdated. It shows there's some ASASTATS locked in Algodex trade but I don't have any order currently opened there. I had one but have cancelled it days ago.

**Comment by ipaleka** [comment]
The full update is made, we'll keep this open until the problem reoccurs.

**Comment by dragmz** [comment]
I can confirm this works as expected now after opening and cancelling a new order on Algodex.

**Comment by ipaleka** [comment]
> I can confirm this works as expected now after opening and cancelling a new order on Algodex.

Can you please give the date when you last time canceled your order?
