### ISSUE TITLE
[D1] Mobile app omits NFT URL if its key isn't among predefined

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#460]
App:
![app1](https://user-images.githubusercontent.com/49662536/217561965-3e3237bd-0a8c-452f-bb4b-983b5fc5fcee.png)

Website:
![web1](https://user-images.githubusercontent.com/49662536/217562002-2fa8aebf-834c-48b9-af60-e680e6b8be1f.png)

Here's the related API response:
```
"urls": {
  "Vault": "https://octorand.com/prime/gen1/039",
  "URL": "https://gateway.ipfs.io/ipfs/QmVJrA5CndUVWuGWsQnpbsV6dtkMuXSuhP9QRj1aozT7jL",
  "Template": "template-ipfs://{ipfscid:0:dag-pb:reserve:sha2-256}"
},
```

Everything seems to be ok if the key is among predefined like external_url, media_url, ...

**Comment by kerrilija** [comment]
Fixed and awaiting deployment.
