### ISSUE TITLE
Add Cometa's Roobies staking program

### ISSUE THREAD

**Issue by BartleDooDerp** [asastats/channel#469]
BartleDooDerp.

Roobies staking Cometa:
https://algoexplorer.io/application/1035503264

Pizza staking Cometa:
https://algoexplorer.io/application/1033498923

**Comment by ipaleka** [comment]
> Pizza staking Cometa:
> https://algoexplorer.io/application/1033498923

https://github.com/asastats/channel/issues/464

**Comment by ipaleka** [comment]
Added ALCH-ALGO LP too.
