### ISSUE TITLE
NFT Collection name doesn't match NFTx or AxN

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#473]
Bug description:

Stats shows the name of the collection as `AlgoArte` whereas other galleries have it listed as `Adventures in AI`

Sample asset Id 830894934

**Comment by ipaleka** [comment]
Here's that entry from our collection data:

```
"830894934": [
    [
        "Adventures in AI ",
        "algogems"
    ],
    [
        "Algo Arcades",
        "algoxnft"
    ],
    [
        "Beats From The Vault",
        "algoxnft"
    ],
    [
        "Adventures in AI",
        "algoxnft"
    ],
    [
        "Junk Food Wars",
        "algoxnft"
    ],
    [
        "AlgoArte",
        "algoxnft"
    ],
    [
        null,
        "custom"
    ]
],
```
Based on that, our algorithm would have surely picked "Adventures in AI", but for some reason I manually put that collection name among the exceptions back in the first days of collections implementation. I've commented out it now, together with some others:

```
(
        "Sold Out" in item
        # or "GEM NFT GALLERY" in item
        or "my collection" in item
        or "Artist Buy Back Reward Collection" in item
        # or "WaterLawOF Universe" in item
        # or "Algomath" in item
        # or "CryptoTrees NFTs" in item
        or "Holder Custom & Special Collab" in item
        # or "Adventures in AI" in item
    )
```

The next update will happen in a day, so this should be resolved then.
