### ISSUE TITLE
[AT3 x 5] Create a tool for multisigning ASA Stats community account

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#477]
DragMZ made it available: https://github.com/dragmz/ams

**Comment by AlgoRhythMatic** [comment]
@ipaleka - just wanted to confirm you intend this to mean 5 x single line entries for [AT3] value for DragMZ such that he receives .15 x 5 = .75 damo?

**Comment by ipaleka** [comment]
> @ipaleka - just wanted to confirm you intend this to mean 5 x single line entries for [AT3] value for DragMZ such that he receives .15 x 5 = .75 damo?

That's right!
