### ISSUE TITLE
[AT3 x 4] Create a ASA Stats community multisig account

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#478]
The following members participated and they are multisigners:

@dragmz 
@AlgoRhythMatic 
@kerrilija 
@SCN9A

**Comment by AlgoRhythMatic** [comment]
@ipaleka - wondering if this is meant to be an [AT3] split 4 ways to count 25% each, or meant to be [AT3] per-person?

**Comment by ipaleka** [comment]
> @ipaleka - wondering if this is meant to be an [AT3] split 4 ways to count 25% each, or meant to be [AT3] per-person?

It's [AT3] for person. :)
