### ISSUE TITLE
Remove YLDY from NFT Prize Game after withdraw 

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#484]
By @SCN9A

**Comment by ipaleka** [comment]
@SCN9A they use Algorand boxes to hold the values, but they simply don't remove the value after the funds are withdrawn.

**Comment by SCN9A** [comment]
@ipaleka 

[Week 2 of the NFT Prize Game](https://twitter.com/YieldlyFinance/status/1628013052330139648?s=20) has been announced. 
Current Escrow RIU7QSBUZTM2P3FKP5YHG2INZNQ54TXTNBMT3A7V6L3G3VFHMDHE67XJX4
YLDY sent there does not show in wallet. 

This is daunting to be fixed manually! Thank you
