### ISSUE TITLE
[B2] Some single mint NFTs are displayed in different wallets

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#500]
Bug description:

I made a couple purchases yesterday and they happened to be from the same seller. When I checked that seller's wallet to see what else they might have, I noticed the ones I bought were still listed there. I then jumped back to mine to verify again and they after multiple refreshes, they appear on both of our wallets. I then checked the owner just before the seller's to see if it would appear on their view and it does not. 

Can I send you the asset Ids in Discord?

**Comment by ipaleka** [comment]
The engine in some cases updates instantly, and sometimes from a few minutes to a few dozen minutes are needed to complete an NFT listing being purchased.

If in your case everything ends as planned, then I believe that my previous sentence explains your issue.

**Comment by moloch10** [comment]
In this case it's been 14+ hours; I just refreshed and still there.

**Comment by ipaleka** [comment]
> In this case it's been 14+ hours; I just refreshed and still there.

Ok, you may send the asset ids to my Discord DM.

**Comment by ipaleka** [comment]
A bug has been located and we'd need to make a full cache update these days.
