### ISSUE TITLE
[F2] Research and implement Venue One

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#506]
### About

> Venue One is a non custodial decentralized prediction protocol built on Algorand that allows participants to take positions on the outcome of real world events. The protocol operates on a set of smart contracts that govern various prediction mechanisms including dual outcomes, speedy  pools and index predictions. The focus is on short to medium duration events in sports and finance.

### The process & asset locking
After signing up, Venue One creates an Algorand address for the user, after he/she clicks "Deposit". Users can deposit USDCa to fund their accounts, and use it to open positions which have an expiry date for "Speedy Markets", "Dual Markets" and also provide liquidity. 

Link to the application:
https://app.venue.one/

About
https://docs.venue.one/

**Comment by ipaleka** [comment]
Very nice looking website with pretty good UI. :)

**Comment by kerrilija** [comment]
> Very nice looking website with pretty good UX. :)

Indeed! The position I opened for testing even gave me a 0.14$ profit! :D Everything works smoothly.

**Comment by ipaleka** [comment]
Do you @kerrilija know how long it takes to finish the whole process upon resolution? Right now my testing entry is labeled "Resolved" for half a day.

P.S. well, there's a button entitled Redeem... xD

**Comment by ipaleka** [comment]
https://docs.venue.one/faq#why-is-there-a-discrepancy-between-my-available-cash-and-the-total-amount-that-appears-in-the-portfo

> The portfolio value represents the total amount of money in your account both in available cash and open positions of dual markets. It only counts the dual markets, as the speedy markets cannot calculate the winnings before the market is closed so it can't be accurate

I guess we should then add Speedy markets amounts as "Provided", and "Amount" for Dual markets.
