### ISSUE TITLE
[T1 + T2] Contact RandGallery and check out the conditions for using their API to fetch listed NFTs prices

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#51]
T1 @SCN9A 
T2 @marucat27 
- - - - -

> https://discord.com/channels/906917846754418770/908054330265960478/958042140305420418

https://discord.com/channels/906917846754418770/908054330265960478/958044217714827324
> Rand's NFT price is available through an API that isn't publicly available (offchain data) and we're going to reach them and ask what are conditions for its use.

**Comment by SCN9A** [comment]
I contacted Rand Gallery by email contact@randgallery.com

Subject: Enquiry Regarding Rand Gallery API utilisation 

Dear Rand Gallery Team, 

I hope all is well. I am contacting you to ask about the conditions for using Rand Gallery API to fetch listed NFTs prices. 

ASA Stats evaluates and presents the current balance for any wallet address on the Algorand blockchain. An explainer video of ASA Stats portfolio tracker is available on  https://youtu.be/M8_dWMNWmCo for reference. 

Thank you for your consideration and forthcoming response.

Kind Regards,
ASA Stats 
https://www.asastats.com/

**Comment by smedury** [comment]
Hi, I'm just noticing this and I'm not sure if you received a response yet. Discord is perhaps the best way to get in touch with Rand and Twitter could be the next best option. Rand is generally busy (like we all are), we can offer to follow up on this if (and when) we get in touch with Rand in the near future :)

**Comment by ipaleka** [comment]
> Hi, I'm just noticing this and I'm not sure if you received a response yet. Discord is perhaps the best way to get in touch with Rand and Twitter could be the next best option. Rand is generally busy (like we all are), we can offer to follow up on this if (and when) we get in touch with Rand in the near future :)

Pretty much status quo then, our @Rach-toomuchgoogling reported pretty much the same during our initial contact back in early January.

Yes, feel free to remind them of our existence, we'd be grateful! :)

**Comment by ipaleka** [comment]
> I contacted Rand Gallery by email [contact@randgallery.com](mailto:contact@randgallery.com)
> 
> Subject: Enquiry Regarding Rand Gallery API utilisation
> 
> Dear Rand Gallery Team,
> 
> I hope all is well. I am contacting you to ask about the conditions for using Rand Gallery API to fetch listed NFTs prices.
> 
> ASA Stats evaluates and presents the current balance for any wallet address on the Algorand blockchain. An explainer video of ASA Stats portfolio tracker is available on https://youtu.be/M8_dWMNWmCo for reference.
> 
> Thank you for your consideration and forthcoming response.
> 
> Kind Regards, ASA Stats https://www.asastats.com/

When you get time, please if you can follow-up.

**Comment by SCN9A** [comment]
I forwarded the message to Kraken#0007, the founder of Rand Gallery, on Discord.

**Comment by lmedury** [comment]
Hey! I followed up with Rand to ask about the conditions to use the API. Awaiting his response.

**Comment by ipaleka** [comment]
to Kraken in Discord DM:

- - - - -

Hello! 

Dunno do you remember me back from those turbulent days on Algorand Discord when I was acting like a "moderator" for the ARC0069 (https://github.com/algorandfoundation/ARCs/pull/38).

I was standing aside watching "bare-knuckles fight" with pretty much only Patrick (now NFD, it looks like he has found some brand new fights to maintain 😆 ) openly against you three guys. It was a normal day in the office until you guys started accusing barnji, I had to get involved afterward. I guess everything went good after all at the end.

Sorry for the long introduction, I'm the founder of ASA Stats and we as a project are facing the far most difficult problem so far since the project started. 

You are using offchain capabilities to record listed NFT prices on Rand Gallery and we are not able to collect those without your support. We have tried to reach you on numerous occasions without any success (https://github.com/asastats/channel/issues/51).

We discuss everything in ASA Stats (even this message will be broadcasted in the above-mentioned thread) and we'd be delighted if we can discuss anything regarding this.

Sincerely,

Ivica

- - - - -

**Comment by ipaleka** [comment]
by Kraken and ipaleka in Discord DM

- - - - -
Hey hey
Are you wanting to show listings for a specific seller?

- - - - -

Hi, thanks for the quick response, I really appreciate that! 🙂

The ASA Stats aims to present every ASA and NFT price on the Algorand blockchain. That's easy for dApps that record listed price on-chain, but for off-chain recording like in your case we'd need your API endpoints.

That being said, we need them all for all the sellers. 🙂

- - - - -

How often are you wanting to get this data

- - - - -

That completely depends on you and your resources, we'd adjust to you.

- - - - -

Cool

- - - - -

**Comment by marucat27** [comment]
In Discord DM with Maru the Cat and Agash.algo:
“We can provide an API like we did for Asalytic”

**Comment by marucat27** [comment]
In Rand Gallery Discord from Agash.algo:
“ We do have API’s available to see all the listings a certain address has made, albeit this is not on chain”

**Comment by ipaleka** [comment]
We've got our API token! :)

**Comment by marucat27** [comment]
Great news! 👏
