### ISSUE TITLE
Mutants v.s. Zombies collection don't show their mint price

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#510]
Bug description:

Most collections show their mint / shuffle price as last purchase; however, this collection does not. 

I suspect it being from shufl.app might be the reason?

I don't know other collections started off shufl so I didn't check if others behave this way.

**Comment by ipaleka** [comment]
Well, I guess we're safe to collect them from that escrow where Al Goanna had sent them and search for atomic swaps.

P236S56XY56N7HJNUNKKQA6PIGSULYZ2JI5LOGNBQDBISKPIWFTYQ3ILRQ

**Comment by ipaleka** [comment]
https://news.shufl.app/al-goanna-mutants-versus-zombies-makes-all-of-algorand-a-winner/
> 24 hours prior to public shuffle was the whitelist drop, which had a total of 2,765 spots. The whitelist remained open for 22 hours, where those with spots could mint their random mutant or zombie for 222A.

**Comment by moloch10** [comment]
Hi, sorry I haven't had a chance to get on this week. Noticed my mutants jumped from the bottom. Looks good, thanks!
