### ISSUE TITLE
NFT collection name wrong on collection creator's view

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#512]
Bug description:

Related to: https://github.com/asastats/channel/issues/473

I noticed other NFTs from this collection were getting labeled incorrectly.

This time, I looked up the [creator's address](https://www.asastats.com/SHFMX2NRDYWYXD4I6Q6MHJHTFQMYT7PBIDC4U7QPNH6M55ZA6UVVAFC354) on Stats and it shows as "Junk Food Wars" when it's [Adventures in AI](https://www.nftexplorer.app/collection?creator=SHFMX2NRDYWYXD4I6Q6MHJHTFQMYT7PBIDC4U7QPNH6M55ZA6UVVAFC354).

Interestingly enough, while getting the links for this ticket ready, I loaded up their wallet again and this time the same collection is labeled as "Algo Arcades."

Creator's address: SHFMX2NRDYWYXD4I6Q6MHJHTFQMYT7PBIDC4U7QPNH6M55ZA6UVVAFC354

Both of these names are in that array of collection names from https://github.com/asastats/channel/issues/473

**Comment by ipaleka** [comment]
Those are set to "Adventures in AI" for the next update.

https://algoxnft.com/collection/algo-arcades
https://algoxnft.com/collection/junk-food-wars
