### ISSUE TITLE
NFTs listed on Rand no longer show in Stats

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#514]
Bug description:

I noticed that an NFT I listed on Rand wasn't showing up in my view. 

I updated the price from its initial listing so to make sure that wasn't the issue, I listed a new NFT without changing the price but it too does not show up. The caveat to this is that it did show up for a minute or two just after listing the item. Refreshing after a few minutes and that same listing no longer shows up in Stats.

I suspect the change from https://github.com/asastats/channel/issues/500 might be the culprit.

**Comment by ipaleka** [comment]
> The caveat to this is that it did show up for a minute or two just after listing the item. 

The problem is in our additional listings checking routine that is buggy and somehow deletes valid listings. This will be prioritized after https://github.com/asastats/channel/issues/453 is deployed.

**Comment by ipaleka** [comment]
> The caveat to this is that it did show up for a minute or two just after listing the item. 

Based on the quote, our additional obsolete listings checking has been removed in the latest update.

I'm leaving this open until you @moloch10 confirm that the same NFTs you tried to list two weeks ago now are shown as they should be.

**Comment by moloch10** [comment]
> > The caveat to this is that it did show up for a minute or two just after listing the item.
> 
> Based on the quote, our additional obsolete listings checking has been removed in the latest update.
> 
> I'm leaving this open until you @moloch10 confirm that the same NFTs you tried to list two weeks ago, when you list them now then they are shown as they should be.

Hi. So the NFT listed on Rand that caused me to open this ticket now shows up correctly on Stats. 😀
However, I now see that an NFT I have listed on AxN is being ignored by Stats. 😑
Let me know if I should send you an asset id.
