### ISSUE TITLE
[F1+F1] Add Humble's Rupiya-Cowrie farm

### ISSUE THREAD

**Issue by Algoworm** [asastats/channel#519]
Feature link:https//humle.sh.farm

Application ID:1056092000
+Cowrie/Paaee.   ID:1056107839

**Comment by ipaleka** [comment]
These two need confirmation of deployment, I can't check Humble as something is wrong with their UI.

    1056092000  
    1056107839  

[This one](https://github.com/asastats/channel/issues/517#issuecomment-1462479227) also needs confirmation that ASA Stats shows the data:

    1055624541

**Comment by ipaleka** [comment]
So, F1+IC for Algoworm and an additional F1 for kerrilija as he confirmed a proper deployment.
