### ISSUE TITLE
Contact Algogems and check out the conditions for using their API to fetch listed NFTs prices

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#52]
> https://discord.com/channels/906917846754418770/908054330265960478/958042140305420418

https://discord.com/channels/906917846754418770/908054330265960478/958044217714827324
> Rand's NFT price is available through an API that isn't publicly available (offchain data) and we're going to reach them and ask what are conditions for its use.

**Comment by SCN9A** [comment]
I contacted Algogems on Discord, sent the following message:

Hi Wilder, I hope all is well. I am representing ASA Stats project. I am contacting you to kindly ask about the conditions for using [Algogems](https://algogems.io/) API to fetch listed NFTs prices. I would appreciate your input on this. 

ASA Stats evaluates and presents ASA and NFT price information on the Algorand blockchain. ASA Stats portfolio tracker https://www.asastats.com/.

Many thanks

**Comment by SCN9A** [comment]
Got response from Wilder on Discord

> I have forwarded this info to our lead dev Audran. TYVM for reaching out

**Comment by ipaleka** [comment]
> Got response from Wilder on Discord
> 
> > I have forwarded this info to our lead dev Audran. TYVM for reaching out

May you ask for additional information, sort of follow-up and maybe get a direct contact information of the dev?

**Comment by SCN9A** [comment]
I contacted the lead dev on Discord kilag#8412

> Hi Audran,  I hope all is well. Wilder may have forwarded my message to you. I am keen to listen to your response.  I am representing ASA Stats project. I am contacting you to ask about the conditions for using Algogems API to fetch listed NFTs prices.  ASA Stats evaluates and presents the current balance for any wallet address on the Algorand blockchain. An explainer video of ASA Stats portfolio tracker is available on https://youtu.be/M8_dWMNWmCo for reference.  Thank you for your consideration and forthcoming response. Kind Regards. ASA Stats  https://www.asastats.com/

**Comment by SCN9A** [comment]
I sent a DM to Wilder on Discord
***

Hi Wilder, 
I am just following up on our request to know the conditions for using Algogems API to fetch listed NFT prices. I didn’t get a response from you since we last communicated. I have contacted Audran on Discord on 29 May but did not receive a reply either.

I understand that you and Audran are busy, but I would appreciate Algogem’s input on this. We just wanted to get in a position to see our options. Thank you

**Comment by SCN9A** [comment]
Got response from Wilder on Discord

> Would you be willing to have a specific dev group on telegram for this integration. I have told Audran once again about this integration, but he insists we use TG.

> We do have API’s that NFTx is using, so this is something we can definitely accomplish.

***
Hi Wilder,
Many thanks for taking things forward. I will share this request with Team and get back to you. Can you please send me TG handler so I can share it with our devs. Thank you

**Comment by ipaleka** [comment]
I'm glad to inform you that guys from Algogems have been very friendly and pointed to the fact that their listed prices are indeed present onchain since they have started using TEAL5. Our first research and implementation happened before that, so we just need to update our research to affect the changes. We'd surely want to use onchain collecting instead depending on API, but it surely a good thing that we can use their API if we encounter major difficulties.

https://github.com/asastats/channel/issues/145
