### ISSUE TITLE
Algodex buy orders are shown even they are not present in UI

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#527]
By kerrilija in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1084890501066522738):

![buy](https://user-images.githubusercontent.com/49662536/224792104-a65c3243-55f7-4644-81b9-65dd52f30cef.png)
![yldy](https://user-images.githubusercontent.com/49662536/224792379-3556ad5e-293a-447d-9ffb-4eca4c3478be.png)

**Comment by ipaleka** [comment]
So YLDY4..JDIA4 created a limit order to buy YLDY and supplied 41.013614 ALGO:

https://algoexplorer.io/tx/group/vePFf6TIZPlBm%2FKIV0R0oNE5paa%2BeV7%2FTIYNPTEZEas%3D

The limit order has been executed 4 times in round 24864449:

https://algoexplorer.io/tx/group/u4wp2MC0RyUdtfnEH0QxWjLM58aq7oQ2VV1VfoXb4%2Bw%3D
10.251152 ALGO

https://algoexplorer.io/tx/group/cZrdlvQggn3qwaD14Mn%2BRrJuInSYRdjYxbhNwgEPCwA%3D
10.251152 ALGO

https://algoexplorer.io/tx/group/ct0VvensnyRxL%2BGu0l8edMoJaIBanoLO22WeSWZbwoQ%3D
10.251152 ALGO

https://algoexplorer.io/tx/group/tT%2FIe1qgLeM8f4U6Xvi%2BcOU8%2FMIiBZtQ1ksEFzFEoQY%3D
10.251152 ALGO

That would have been closed order, but then comes the following transaction:

https://algoexplorer.io/tx/UKLB7ZB4XHTIID64JQNAN3DH7TETRG24W767GXOCIBJT7IN5FVMA

where the creator sent 42.163347 ALGO to the escrow for an unknown reason.

Our engine doesn't collect all the executes, it just checks the escrow's funds so this weird transaction messes up our records.

**Comment by ipaleka** [comment]
Majority of problems are resolved, tho there exists problem with orders that are still onchain but not shown in Algodex UI: https://discord.com/channels/906917846754418770/910524302531649566/1086294098081751041

**Comment by kerrilija** [comment]
by Garywontwin on [Reddit](https://www.reddit.com/r/asastats/comments/12vql8t/algodex_issue/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button)

> I noticed that if I create an order on Algodex it is calculated correctly on asastats but if I cancel the order asastats still shows a balance on Algodex even though I recieved my funds.

**Comment by ipaleka** [comment]
https://github.com/asastats/channel/issues/586
