### ISSUE TITLE
[B2] Wrong USD equivalent & delays with updating asset amounts

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#539]
1) Tapping on total Algo displays a price of 0.205$ while Algo is around 0.22$. This happens regardless of having USDC in a wallet. 

2) If the amount of an asset is changed in a wallet, it takes at least 10 minutes to update the real balance

**Comment by ipaleka** [comment]
I've tried to install another Node on our cache server to speed up cache updating, but as it seems that affects our main cache server Node instance.
