### ISSUE TITLE
Create index page slogan explaining that all the ecosystem liquidity is evaluated

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#541]
As the title says, we'd need a sentence that explains how all the ecosystem liquidity is used to evaluate user accounts.

Right now there are only two sentences:
"All your Algorand assets on one dashboard"
"Your entire Algorand portfolio in one place"

**Comment by kerrilija** [comment]
Well, ChatGPT is our friend :D

"Maximize your account's potential with ecosystem-wide liquidity evaluation."

"Evaluate your account's potential with ecosystem-wide liquidity assessment."

"Explore your account's potential with ecosystem-wide liquidity check."

**Comment by ipaleka** [comment]
Give me a teenager's construction rather than toddler's... xD

Users don't check liquidity, we use it to evaluate their accounts. And maximize is a verb, if we need to use the same base then we'd use it as an adverb "Show the maximum value".

**Comment by kerrilija** [comment]
How about...

"The maximum value of your assets extracted using the entire ecosystem liquidity."

?

**Comment by ipaleka** [comment]
Yep, we're closer now.

I'm not sure if would we be able to achieve that in one slogan, but also a fact is that we present all the liquidity even when tokens are locked...

**Comment by ipaleka** [comment]
> The maximum value of your assets extracted using the entire ecosystem liquidity.

Can we get something else instead of "extracted"? I mean, *evaluated* would be the verb of my choice, but at the same time "maximum value" is surely a phrase we have to use.

If no other suggestions arrive today, I'd close this issue and deploy.

**Comment by kerrilija** [comment]
"The maximum value of your assets $extracted$ using the entire ecosystem liquidity, even for locked assets."

Instead of "extracted"... The most accurate would be "calculated".

Other options:
- gathered
- displayed
- evaluated
- assessed
- computed
- aggregated

**Comment by ipaleka** [comment]
> * aggregated

:)

**Comment by AlgoRhythMatic** [comment]
Is the [F1] just for the first part, or for the whole exchange of this task?  Just trying to understand if there is some [CT] time-based aspect to it based on the jump in time from 3 weeks ago -> 2 weeks ago, etc?

**Comment by ipaleka** [comment]
> Is the [F1] just for the first part, or for the whole exchange of this task? Just trying to understand if there is some [CT] time-based aspect to it based on the jump in time from 3 weeks ago -> 2 weeks ago, etc?

Well I thought F1 is for the whole task, but feel free to suggest CT1 if you think it's a better fit...

**Comment by AlgoRhythMatic** [comment]
I think F1 is fine - just wanted to be sure based on it being in body vs. header.  Thanks!

**Comment by AlgoRhythMatic** [comment]
On 2nd thought, I'll split the difference and make it an F2 due to back and forth...
