### ISSUE TITLE
Assets involved in multiple dApps are not sorted by value

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#55]
They are listed by pool age instead.

**Comment by ipaleka** [comment]
Btw, a topic for rewards discussion in the cycle when this will be resolved, this issue was requested internally and so added to https://github.com/asastats/docs/blob/main/reported-bugs.md, and the following request was added afterward:

https://discord.com/channels/906917846754418770/915342738201931836/935245337784889374

**Comment by AlgoRhythMatic** [comment]
Based on the EXISTS marked on the Discord comment related to this suggestion, I'd say that it does not need to be rewarded.  Is there any trail of the internal (original) request that should be rewarded?

**Comment by ipaleka** [comment]
> Based on the EXISTS marked on the Discord comment related to this suggestion, I'd say that it does not need to be rewarded. Is there any trail of the internal (original) request that should be rewarded?

It was requested by me internally so I guess no rewards are needed to allocate.
