### ISSUE TITLE
[D2] Allow NFT amounts to be float numbers

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#573]
Right now if a float is sent in API response then an error is raised, like in this example

https://www.asastats.com/6IW52JMHBXAWPFIAZTP6EVHZT43LA2HX7DKGOV56BXJCWCGGD2BZIV625I

for the 468359924:

```"nft_values": [{
  "value": 13344.0,
  "collection": "Alchemon",
  "amount": 238.0,
  "nfts": [{
  ...
...
{
  "value": 0,
  "id": 468359924,
  "amount": 0.01,
  "nft": {
    "id": 468359924,
    "name": "ART: MagicaL Bolt",
    "unit": "ART6",
    ...
```

As a temporary solution, we've prevented raising error by converting those amounts to integers in API responses.

**Comment by ipaleka** [comment]
After mobile app deployment, check if the same format is shown on the website too (like amount of 237.01 Alchemon for 6IW52JMHBXAWPFIAZTP6EVHZT43LA2HX7DKGOV56BXJCWCGGD2BZIV625I)

**Comment by kerrilija** [comment]
Fixed and awaiting deployment.
