### ISSUE TITLE
Switching to Algoscan

### ISSUE THREAD

**Issue by wxivd** [asastats/channel#590]
AlgoExplorer is discontinuing API Service

https://twitter.com/algo_explorer/status/1651255617368072194

> We regret to inform you that our API service will be discontinued on June 15th, 2023. We understand that many of you rely on this service and apologize for any inconvenience this may cause.
> 2/2 We encourage you to transition to alternative API solutions before the deprecation date to ensure a smooth transition.   Thank you for your understanding and continued support!

**Comment by ipaleka** [comment]
This doesn't mean that they're going to rid of their core, the website we link on our pages, it's just that they won't provide any more API for the third-party developers.

Tho we use their API internally to fetch NFT data and some dApps unavailable through our running Node instance. I can use this issue as a memo to switch completely to AlgoNode.

**Comment by ipaleka** [comment]
AlgoExplorer has got some difficulties rendering its pages, so I'm renaming this to the original title and switching to the original change, and a new issue will be created for switching to AlgoNode.
