### ISSUE TITLE
Some NFTs listed for sale on AxN aren't shown on Stats

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#593]
Bug description:

There's an option on algoxnft.com to reduce the price of an already listed NFT; those NFTs no longer appear.

I can DM you some asset ids if needed.

**Comment by ipaleka** [comment]
Feel free to send them, tho our testing account should be powered for that anyway.

**Comment by ipaleka** [comment]
It is implemented, the process consists of removing the old listing and sending it to a new escrow, so there will be a period of a few minutes when maybe ASA Stats will show a double quantity.
