### ISSUE TITLE
Allow user to create custom NFT collections

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#594]
I collect NFTs not just based on their official collection. 

I have my own dashboard where I can group them according to my own definitions.

Would be great to do the same on Stats so that they can be showcased as desired and not just spread out across numerous "meaningless" collection groupings / accordions.

**Comment by ipaleka** [comment]
This is for sure a nice feature, but imo it should be implemented as a user widget, not as a core functionality, therefore I created a feature request here: https://github.com/asastats/channel/wiki/FeaturesDependentOnUserWidgets#custom-nft-collections

**Comment by ipaleka** [comment]
P.S. the thing is that our development resources are limited. Once we develop this widget if the DAO decides so, we can move it to free/core. And that applies for all the user widgets.

**Comment by moloch10** [comment]
Ahh yes, forgot about that page.

**Comment by moloch10** [comment]
> P.S. the thing is that our development resources are limited. Once we develop this widget if the DAO decides so, we can move it to free/core. And that applies for all the user widgets.

This is something I already have work in a basic form. I think implementing it on the site wouldn't be too difficult once the standard for how to define these collections is decided.

**Comment by ipaleka** [comment]
> > P.S. the thing is that our development resources are limited. Once we develop this widget if the DAO decides so, we can move it to free/core. And that applies for all the user widgets.
> 
> This is something I already have work in a basic form. I think implementing it on the site wouldn't be too difficult once the standard for how to define these collections is decided.

Absolutely, after we decide on the technology and format for user widgets it should be easy enough to implement a majority of those requested widgets if the logic is already known.

**Comment by ipaleka** [comment]
OP will be referenced in an issue from the dependent feature.
