### ISSUE TITLE
Display larger view of NFT when hovering over one of the thumbnails in collapsed view

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#595]
Rather than expanding and having to find the NFT, it would be great to be able to hover any of them and see a larger preview.

Example:

![image](https://user-images.githubusercontent.com/97535612/235189018-9c649c34-27fa-4bde-928d-9cccdda4fb2d.png)

**Comment by ipaleka** [comment]
Done, tho the padding is yet to be removed.
