### ISSUE TITLE
[AT2 + AT1] Send rewards funds for the second quarter to the GARD escrow from the community multisig account

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#621]
dragmz and kerrilija

**Comment by AlgoRhythMatic** [comment]
Would you classify this as an AT2 (30-60m to complete)?

**Comment by ipaleka** [comment]
> Would you classify this as an AT2 (30-60m to complete)?

Dunno, it comes down to importing a phrase to Defly, importing one hash string, and a final confirmation. Maybe preparing hash takes more time, done by @dragmz .

**Comment by AlgoRhythMatic** [comment]
So then probably AT2 + AT1

**Comment by ipaleka** [comment]
> So then probably AT2 + AT1

Done! :)
