### ISSUE TITLE
Folks Finance closed position of Folks borrow USD still shows positive 

### ISSUE THREAD

**Issue by SCN9A** [asastats/channel#63]
https://discord.com/channels/906917846754418770/910524302531649566/972898061275787304

By Tink in Discord
> I borrowed usdc but then closed my position. It still shows up.
> And shows up as a positive instead.

by SCN9A in Discord
> This could be synching issues. when did you close your position?

By Tink in Discord
> Weeks ago.

**Comment by ipaleka** [comment]
This problem is resolved, tho we still need to fix the [returned borrows and withdrawn deposits](https://github.com/asastats/channel/issues/67) interest issue.
