### ISSUE TITLE
[B2] Listed NFTs on Rand and Shufl are not tracked

### ISSUE THREAD

**Issue by wxivd** [asastats/channel#630]
Bug description:
NFTs listed on R& and Shufl does not show up on portfolio tracker. The total number of NFTs owned does not include listed items. 

Though listing on algoxnft and Octorand works as expected

**Comment by ipaleka** [comment]
A small update for the Rand part...

First of all, Rand has changed its former policy that only 1/1 NFT can be listed, so for that part a solution is straightforward.

The problem we have got with other listed and not shown NFTs is probably in the routine that checks for listings validity - our engine has collected those that miss when we run the update. So, after 1/1 problem is deployed, a cache update will be processed and for some time everything will be ok until that flaw in listings checking takes place. That's kind of good news as we don't have any problem with Rand's API or something similar out of our reach.

P.S. of course, it could be that our engine leaning on 1/1 policy causes listings checking problem, more news about this tomorrow.

**Comment by ipaleka** [comment]
RandGallery doesn't provide any UI for a non-1/1 listed NFT if someone else listed the same NFT for a smaller price. So, we'll present such an NFT on ASA Stats as listed on RandGallery and set the correct price, but the link will lead to a different NFT, one with a smaller price.

**Comment by ipaleka** [comment]
Shufl changed the way how NFTs are listed. The old smart contracts were created by their escrow upon user clicking to list them, while recent smart contracts are kind of pre-created and then just filled up upon a user lists an NFT.

**Comment by ipaleka** [comment]
Both providers' bugfixes are deployed, tho we can't be sure those are the only ones that caused the problem. I'm closing this, please open another issue if you encounter another problem.
