### ISSUE TITLE
[B1+B1+B1] Wrong proxy pools values for some of ASA

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#631]
By motuwagon in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1113058171016196146):
> Have a couple defunct project ASA showing more value than actual.   Lunar 416737271 and aShib 
388505064

By motuwagon in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1113252397775601735):
> Another incorrect value,  Odd one going to  Sea Yacht

- - - - -

By Mocha in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1118285992906997830):

> Pricing for Wormhole WBTC is WAY off  it doesn't even show on Vestige at all https://algoexplorer.io/asset/1058926737

> WBTC should be closer to $194...perhaps a new Oracle or however y'all fetch the price? ):
<img src="https://github.com/asastats/channel/assets/49662536/5230aa16-039f-41b7-b3d5-b4b35b101122" width="250">

**Comment by ipaleka** [comment]
Indirectly connected with: https://github.com/asastats/channel/issues/624

**Comment by AlgoRhythMatic** [comment]
Is this 2 x B1 for motuwagon and 1 x B1 for Mocha?

**Comment by ipaleka** [comment]
> Is this 2 x B1 for motuwagon and 1 x B1 for Mocha?

Yes, that's correct!
