### ISSUE TITLE
Refresh mutable NFTs' image more frequently

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#637]
With the release of shitty cities which allow a user to build on and change their NFT, the static preview image doesn't match up to what the actual NFT is. ARC data is correctly displayed according to new settings but again, don't match up with the image.

**Comment by ipaleka** [comment]
They are collected every 30 minutes, do you have some IDs that haven't been updated?

**Comment by moloch10** [comment]
Sure. Will send via DM.

**Comment by ipaleka** [comment]
So basically this is a different kind of problem... This was resolved by refreshing the page with Ctrl+R.

We set the cache duration for NFTs to a long period. If we can manage to distinguish and predict those durations, we can create a few other cache duration classes.
