### ISSUE TITLE
[F2] Show all Shitty City Blocks

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#638]
Shitty Cities have nine spaces which can be filled with a Shitty City Block.

When a block is added to a city, that block is sent off to the project's vault address [SCBVCREF5NK2RBU3ERYRA4PY42ZIXXTHPKQ7DATKKWI4THUTCBJ23DMEAE](https://www.asastats.com/SCBVCREF5NK2RBU3ERYRA4PY42ZIXXTHPKQ7DATKKWI4THUTCBJ23DMEAE) which holds everyone's blocks; however, this block is still "owned" by the original user.

The blocks that comprise a city are defined in said city's ARC tags, for example:
![image](https://github.com/asastats/channel/assets/97535612/2676b396-2a71-46be-a4d4-7b7c3e28fd5a)

It would be nice to include those blocks in Stats and possibly to denote somehow that they aren't "free."

**Comment by ipaleka** [comment]
I'm not familiar with Shitty Cities and I can't comprehend from your comment what exactly we need to do, which information we should show and where exactly. Can you please explain in detail how you think we should do that?

**Comment by moloch10** [comment]
Hi, here are the details:

Each Shitty City has nine spots and each spot can hold a single Shitty Block. 

With the [Shitty City Builder](https://www.shittycities.art/builder), a user can create their own custom city by positioning whatever blocks they have in any configuration to make up the Shitty City. 

When the desired city is finalized, all of the blocks that were selected to make up that custom city are sent off to the [Shitty Vault](https://www.asastats.com/SCBVCREF5NK2RBU3ERYRA4PY42ZIXXTHPKQ7DATKKWI4THUTCBJ23DMEAE).

The Shitty Vault holds the blocks for all the users' custom cities. When a spot is emptied out, the original block gets sent from the vault back to the user. Also, if it's switched for another block, then the vault sends back the original and in addition, the replacement gets sent into the vault. 

When viewing a city, the ARC tags will show each of the blocks that make up that city which are of course vaulted and those assets aren't shown under Shitty Blocks because they're not in the wallet. 

So the request is to show / consider / calculate those vaulted Shitty Blocks because they are owned by the user. 

Hopefully that made sense. There's a short clip on how these work in their [documentation](https://docs.shittykitties.art/collections/shitty-cities) in case it's not fully clear. 

Thanks

**Comment by ipaleka** [comment]
> So the request is to show / consider / calculate those vaulted Shitty Blocks because they are owned by the user.

Not that we're going to do that, but just to clarify things, in theory, we can just parse a user city's metadata for blocks' ids and add them to the user's account, right?
<img src="https://github.com/asastats/channel/assets/49662536/f88c70a8-9455-4f3b-af2a-928073e23b74" width="420">

Those blocks will be, as you said, under the user's Shitty Blocks collection. I guess with a link "Shitty Vault" just the way we present NFTs that are inside Octorand vault. 

Those blocks that aren't inside a city, as well as Kitties living in, are present in the user account so we don't need to do anything about them.

**Comment by ipaleka** [comment]
I'm afraid I've missed some crucial information about the process.

Here's an address https://www.asastats.com/JGUOE3YPUEFU2K5JVU3N7E6GEKS2M4MO7MQHVX63W73GIPP6Y6QUNOFE2Y

Here's its total from and to the vault (negative value means the vault sent it to the address):
```
1102797240;-1
1102796294;-1
1102794533;-1
1102792170;-2
1102790500;-1
1102792980;2
1102796409;-1
1102791944;-1
1102797274;-1
1102796135;-1
1102794167;-2
1102792258;-1
1102792150;-1
1102797573;8
1102796615;1
1102796177;1
1102797506;1
1102796452;1
1102796093;1
1102796063;1
1102791858;1
1102790776;1
```

That total fills two cities:
```
Block #1: Rundown House - 1102797573
Block #2: Rundown House - 1102797573
Block #3: Rundown House - 1102797573
Block #4: Rundown House - 1102797573
Block #5: Garbage Dump - 1102796615
Block #6: Rundown House - 1102797573
Block #7: Rundown House - 1102797573
Block #8: Rundown House - 1102797573
Block #9: Rundown House - 1102797573

Block #1: Backyard Wrestling Ring - 1102792980
Block #2: Tree House - 1102796063
Block #3: Haunted House - 1102796093
Block #4: Petting Zoo - 1102796452
Block #5: Backyard Wrestling Ring - 1102792980
Block #6: Pyramids - 1102797506
Block #7: Mini Golf - 1102790776
Block #8: Nightclub - 1102791858
Block #9: Football Field - 1102796177
```

But this one is filled with blocks I can't comprehend the sources:
```
Block #1: Two Story Red House - 1102795893
Block #2: One Story White House - 1102795063
Block #3: Two Story Green House - 1102796294
Block #4: Two Story Townhouse - 1102795263
Block #5: High School - 1102795494
Block #6: Office Building - 1102796577
Block #7: One Story Green House - 1102797371
Block #8: Trailer Park - 1102793644
Block #9: Rundown House - 1102797573
```

**Comment by ipaleka** [comment]
> I'm afraid I've missed some crucial information about the process.

Good news, it looks like the "problem" is only in our metadata collecting process that isn't in real-time.
