### ISSUE TITLE
Wrong COOP price in Defly orders

### ISSUE THREAD

**Issue by Algoworm** [asastats/channel#650]
Bug description:Wrong price for defly orders.....coop (defly orders for coop) indirectly every coin who have pool with coop-wrong.

-----
By TallWomble in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1121016700352086116):
> what does "Defly orders" mean in the balances detail? I can see "Defly limit orders" on a couple of ASAs which look right, but i think i've got an very incorrect total (much larger) for COOP showing on ASAStats. I don't think i have any defly orders at all for coop atm, but it's adding a big total for something.
> ASAStats is showing a MUCH higher wallet value (in Algo) than Pera or Defly. like 25% more.

**Comment by ipaleka** [comment]
https://discord.com/channels/906917846754418770/908054330265960478/1121023517991911464

> For the last 3-4 weeks, redesign of our AMM proxy pools functionality has been developed. It's the basis for everything and fixing other value related issues before it's been finished could be hard and even pointless. The redesign is going to be deployed this week and afterwards issues with Defly and Algodex we have got will be prioritized. 
> Meanwhile, I just removed Defly and Algodex entries from liquidity, and that should make COOP price closer to the right value.

**Comment by ipaleka** [comment]
One issue with Defly is resolved, but the deployment will probably wait for proxy pools redesign deployment in order to check if that was the one that caused your problems.

**Comment by ipaleka** [comment]
The plan is changed slightly and fixes for Defly, Algodex, and Cables Finance are deployed before the proxy pools redesign. Please check your values.
