### ISSUE TITLE
Add Cometa's farming(THC/COOP>PEPE+ALGO) and staking(TENDIES) programs

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#663]
By Milesmile in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1123177115450343454):

> New farms and stake on Cometa. Seems mainly tendies.

THC-COOP LP > PEPE + ALGO Farming program:

Feature link:
https://app.cometa.farm/

Application ID:
1134936223

---

TENDIES > TENDIES Staking program:

Feature link:
https://app.cometa.farm/stake

Application ID:
1134745460

**Comment by ipaleka** [comment]
\+Tendies-ALGO, Tendies-COOP, and WOOD-Tendies farm
