### ISSUE TITLE
Wrong value of Tendies Token (1099533497)

### ISSUE THREAD

**Issue by Algoworm** [asastats/channel#685]
Bug description:Value of Tendies coin at Asastats is twice higer then tinyman,vestige (maybe Lp with Coop and Wood make problems )

**Comment by ipaleka** [comment]
Which Tendies? The one with ID 154338190 that has got a staking program on Cometa is correctly evaluated.

**Comment by ipaleka** [comment]
This problem is resolved in practice as the proxy pools functionality is temporarily removed. Proxy pools functionality need a redesign.
