### ISSUE TITLE
Add Algofi STBL-USDC stability pool

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#7]
@RanTask [in Discord](https://discordapp.com/channels/906917846754418770/908054304332603402/966310592325505055):
> Hi, the new Algofi stability pool for STBL-USDC is missing in Asastats

**Comment by ipaleka** [comment]
This also implies changed link for STBL-STBL to https://app.algofi.org/stability .

**Comment by AlgoRhythMatic** [comment]
Type: [F1]
Recipient: RandomTask (Discord) - 100%
