### ISSUE TITLE
Gas-coop pool wrong value

### ISSUE THREAD

**Issue by Algoworm** [asastats/channel#711]
Bug description:Wrong value GAS(id:1144340594)-Coop coin

**Comment by ipaleka** [comment]
We have got a bug that causes proxy pools values to decay over time so we reset the cache once or twice per day. Please check now and see that your pool value fits.

I'm going to merge this issue with #688

**Comment by Algoworm** [comment]
Sad je sve Ok

pon, 24. srp 2023. 22:45 Ivica Paleka ***@***.***> je napisao:
