### ISSUE TITLE
Communicate with Algodoggo to remove "Clawbacks or Freeze possible!" remark

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#72]
by SCN9A
>  https://www.algodoggo.com/asa/393537671 . notice down "Clawbacks or Freeze possible!" we know that is not correct? Shall I contact them and ask for it to be removed? with reference to FAQ

**Comment by SCN9A** [comment]
I sent a message to AlgoDoggo on Discord:

Hi AlgoDoggo,  I hope all is well.  I am representing ASA Stats project. I am contacting you to kindly request a correction of the supply statistics of ASA Stats token that is shown on https://www.algodoggo.com/asa/393537671.  The webpage displays the following statement: “Clawbacks or Freeze possible!"  Please notice that ASA Stats token Clawback and Freeze were removed permanently on the [24th of November, 2021](https://algoexplorer.io/tx/N4PX4NDYKEFV3LUWDPPHA23HLHTCBEWRQFVCEQUEINJKKUSLQA6Q).   I would really appreciate your time addressing this issue at your earliest convenience.   Many Thanks.

----

AlgoDoggo addressed the issue quickly, reply in Discord
> "Done, this bug affected every asa actually. Thanks for the report"

---

"Clawbacks or Freeze possible!" remark has been corrected to: No Clawbacks or Freeze.
