### ISSUE TITLE
Not recognized collections and NFTs in not-evaluated section

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#722]
NOTE: We'll keep this open on a rewards cycle basis. New entries can be added as comments here.

Q: What does have to happen that a NFT is included in the NFT section instead of the not evaluated section?  

A: It needs to be listed/purchased on some of NFT markets we track or we can simply add it manually. 

-----
[F1]
 
By RandomTask in [Discord](https://discord.com/channels/906917846754418770/973245225680109588/1137464292837425293):

> This one seems stuck in not evaluated: https://twitter.com/goplausible/status/1687571719324610560?s=61

-----

**Comment by AlgoRhythMatic** [comment]
> NOTE: We'll keep this open on a rewards cycle basis

Just want to confirm: after marking this single F1, should I now mark this as "archived"  or let it float for multiple rewards cycles (to check next time for new comments)?

**Comment by ipaleka** [comment]
Please label it as archived and we'll open a new one if/when a new request arrives.
