### ISSUE TITLE
[B1+D1] Show all and ASA sections are not populating after the latest mobile app update

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#724]
By cmjcod in [Discord](https://discord.com/channels/906917846754418770/1014986999578505258/1138358712436793465):

> my app on android just pushed an update from the play store and only nft section is loading now.  "show all" and "asa" are not populating.

**Comment by kerrilija** [comment]
#425

**Comment by kerrilija** [comment]
related to #425

**Comment by kerrilija** [comment]
Resolved with latest build (0.6.3+24)
