### ISSUE TITLE
Change default blockchain explorer back to AlgoExplorer

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#733]
by kerrilija in [Discord](https://discord.com/channels/906917846754418770/973245314687434832/1140883411054100541):
> AlgoScan stops operations on Aug 31

<img src="https://github.com/asastats/channel/assets/49662536/10945d56-c2e3-439f-9375-ca77aefce5c5" width="200" />

**Comment by AlgoRhythMatic** [comment]
@kerrilija or @ipaleka - any idea what to classify this as?  Is this closest to an F?  As well, what was the effort?

**Comment by kerrilija** [comment]
If it's rewardable, it's something like an [F1] (came across the tweet and just posted the SS on Discord).

This is like a notification to the development team (services that are no longer available, major technical changes in the ecosystem etc.). It's not an [AT] or [F], but a bug would appear if no action was taken.

**Comment by ipaleka** [comment]
Yes, this could be a special case regarding the nature (a feature that will become a bug?), but let's just set F1 then.

**Comment by AlgoRhythMatic** [comment]
Thanks, recorded it!
