### ISSUE TITLE
[B1+B1] Wrong value in ALGO for $SILVER and X-NFT

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#750]
By UncleDooom in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1146000245906477077):

> Asastats shows a false value for $SILVER #246519683. 
> I think thats actually about 3870 Algo, not 2484. 
> If converted from Silver -> GoUSD -> Algo

-----
By mileri in Discord DM:

> x-nft value is wrong

**Comment by ipaleka** [comment]
Yep, SILVER's best-value liquidity pool is xUSD which happens to not have an ALGO pool so our latest update to the engine needs an additional fix.

**Comment by ipaleka** [comment]
This problem is resolved in practice as the proxy pools functionality is temporarily removed. Proxy pools functionality need a redesign.
