### ISSUE TITLE
[AT2 + AT1] Send rewards funds for the third quarter to the GARD escrow from the community multisig account

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#755]
dragmz and kerrilija

**Comment by AlgoRhythMatic** [comment]
Hello!  Is this meant to be read left -> right as AT2 for dragmz, and AT1 for kerrilija - or an AT2+AT1 each?

**Comment by ipaleka** [comment]
Left to right please, let's assume that for the latter case, we'll be marking like 2xAT2 + 2xAT1.
