### ISSUE TITLE
Research Coin Market Cap icon links format for available ASA

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#77]
https://discord.com/channels/906917846754418770/915342738201931836/976113077827293204
> I hereby suggested that, Since choice coin and other algo token has been listed on CMC. Pls can you  have the url embedded on asastats for quick check (just as we have it on algo when clicked)

**Comment by moloch10** [comment]
You just need the links to for the different tokens right? 

For example:

CHOICE -> https://coinmarketcap.com/currencies/choice-coin/
DEFLY -> https://coinmarketcap.com/currencies/defly-token/
...
YLDY -> https://coinmarketcap.com/currencies/yieldly/

and so on for every asset that's on their platform?

**Comment by ipaleka** [comment]
That's right.

It would be great if we could have a system we can lean on without the need for manual updating.

**Comment by ipaleka** [comment]
> Regardless, I did find a page that lists a bunch of their supported Algorand tokens.

Can you please supply that link?

We're not use a custom-made list. If we're going to use such things then that will be a GitHub repo under asastats organization and entries formatted like https://github.com/tinymanorg/asa-list.

**Comment by moloch10** [comment]
> Can you please supply that link?

https://coinmarketcap.com/exchanges/tinyman/

> We should avoid using a custom-made list. If we're going to use such things then that will be a GitHub repo under asastats organization and entries formatted like https://github.com/tinymanorg/asa-list.

Oh CSV was just example; if you set up the repo, I'll load the data.

**Comment by ipaleka** [comment]
> > Can you please supply that link?
> 
> https://coinmarketcap.com/exchanges/tinyman/
> 
> > We should avoid using a custom-made list. If we're going to use such things then that will be a GitHub repo under asastats organization and entries formatted like https://github.com/tinymanorg/asa-list.
> 
> Oh CSV was just example; if you set up the repo, I'll load the data.

Well, I didn't understand that you're talking about their pretty much official Algorand ASA listing page.

As defined before, we'd always prefer a system rather than a manual update, so we'll be scraping that page on a daily basis.

Thanks!!
