### ISSUE TITLE
Swap link for Pact no longer works, page loads with an error

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#773]
Bug description:

Looks like Pact has changed their URLs again. When clicking on the swap link, I get the following error:
![image](https://github.com/asastats/channel/assets/97535612/a7dfe304-b7ce-483c-961a-3b149aac344a)

URL goes to: https://app.pact.fi/swap?pair=-ALGO:0/ASA+STATS+TOKEN:393537671(30,CONSTv201)

When selecting the assets, the URL shows up as: https://app.pact.fi/swap?pair=ALGO:0/ASA+STATS+TOKEN:393537671

**Comment by ipaleka** [comment]
The link is actually good, but if you have got smart router selected (and saved automatically by your browser) then it fails. Try with set it to off.

This problem is unresolvable, we have to provide the exact pool (without smart router), while we can't change the user's saved state.

**Comment by moloch10** [comment]
Interesting. I had no clue about that and had to look for that option and when I toggled it off, link's good. 
Thanks for the clarity.

**Comment by ipaleka** [comment]
No problem mate, tbh I spent some time on this, first figuring out the problem and then also contemplating about an eventual solution. :)
