### ISSUE TITLE
[B1+IC1+D1] Mobile app returns a status code 401

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#778]
By robbie in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1155129171962495047):

> Anyone having issues with the android app?

![Screenshot_20230923-091112](https://github.com/asastats/channel/assets/82002056/98f8e253-5ef0-40b8-9635-8de064144f3f)

The issue seems to be with the API token that is being used by mobile app. 

I've tried getting a response using:
- my personal API token - succeded
- API token being used by mobile app - failed

**Comment by ipaleka** [comment]
Argh, the key has expired, I'm sending you a new one @kerrilija.
