### ISSUE TITLE
[B1+IC1+D1] Mobile app: Unable to parse API response

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#785]
By DingusMungus in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1157070460140396544):

> Getting odd errors in the android app. Was a 401 error, updated the app in playstore, and now getting unable to parse api response.

**Comment by kerrilija** [comment]
@ipaleka
I believe the issue is with the API response. If the last purchase on EXA Market is 0, value for key "price" under "last" is an int ("0") while mobile app expects "0.0". If the price is not 0 for the last purchase, it is displayed properly as a float, for example price of 45 is "45.0".

Problem appears on NFTs with these IDs, only for EXA Market, only on Last Purchase:

270162915
791381678
871338642

**Comment by ipaleka** [comment]
@kerrilija The bugfix is deployed and all the zero value entries are sent as float now. Can you check?

**Comment by kerrilija** [comment]
Checked on all of three known problematic addreses, and mobile app now works, as expected.

**Comment by ipaleka** [comment]
Great teamwork then. :) I guess you'll wait for DingusMungus response before closing this...

@AlgoRhythMatic I guess labeling is straightforward as B1 is for DingusMungos, IC1 for kerrilija as the issue creator, while D1 is kerrilija's work on debugging the problem. I suggest we use the same D1 (or D2) for problems where kerrilija finds a solution no matter if he has done the mobile app deployment too or not.
