### ISSUE TITLE
[B1] Add additional digits of precision on the USD/ALGO price

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#788]
By DingusMungus in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1158492781329784934):

> Odd request. Can we get two additional digits of precision on the USD/ALGO price? Two digits make sense for rounding total values, or when algo price is over a dollar, but not helpful for a single algo price. Any change in price less than 10% is not reflected when the price is 10 cents and there is only 2 digits of precision. Thanks!
<img src="https://github.com/asastats/channel/assets/49662536/a9a50e8d-b1b5-4899-a011-a3b5757828aa" width=400>

> The app already shows full precision.
<img src="https://github.com/asastats/channel/assets/49662536/711cfd61-560f-40ac-b4bc-6b621f6307ff" width=400>

**Comment by ipaleka** [comment]
Also set in total amount tooltip.

**Comment by kerrilija** [comment]
This should then be [F1]/[B1]? :)

**Comment by ipaleka** [comment]
> This should then be [F1]/[B1]? :)

He he... It's just a bug, so B1. :)

**Comment by AlgoRhythMatic** [comment]
So B1 for Dingus, D1 for @kerrilija - but who is the IC1 for (looks like @ipaleka originated this issue here)?

**Comment by kerrilija** [comment]
I think this was confused with another issue (#800). I don't get anything for this, I didn't develop anything related to this issue. This is just a B1.
