### ISSUE TITLE
Include a link to nftexplorer.app next to each NFT ...

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#79]
similar to how each asset includes a link to Tinychart.

![image](https://user-images.githubusercontent.com/97535612/168890108-bda09929-15a2-4d40-9638-cb1a82a8dbec.png)

The details on that site are excellent and I find it to be equivalent to Tinychart.

**Comment by ipaleka** [comment]
We won't implement this without a proper discussion. Please open it.
