### ISSUE TITLE
Research and implement Ultraswap positions from Folks Finance 

### ISSUE THREAD

**Issue by garywontwin** [asastats/channel#797]
Feature link: https://app.folks.finance/ultraswap

**Comment by ipaleka** [comment]
That "Convert" functionality has probably used Pact (https://github.com/asastats/channel/issues/738), but those up and down positions (long-short; Silo used the terms call and put, while Algorai uses bull and bear) need to be developed.

**Comment by ipaleka** [comment]
It is developed, and the deployment will probably take place tomorrow during the day or night.

Our data and Folks' can be compared only partially for now as they show only the value of the collateral (or borrow for down) on the [positions' page](https://app.folks.finance/ultraswap):

> The position quantity represents the total amount to which your ultraswap position is exposed. Specifically, it corresponds to the collateral of your loan in the case of an UP position and the amount borrowed on your loan in the case of a DOWN position. The amount refers to the time at which the position was opened. Below in brackets is shown the position size, i.e. the countervalue in USDC at this time.The position quantity represents the total amount to which your ultraswap position is exposed. Specifically, it corresponds to the collateral of your loan in the case of an UP position and the amount borrowed on your loan in the case of a DOWN position. The amount refers to the time at which the position was opened. Below in brackets is shown the position size, i.e. the countervalue in USDC at this time.

**Comment by ipaleka** [comment]
Hi @garywontwin !

Rewards cycle ended (https://github.com/asastats/channel/discussions/819) and I'll need your public Algorand address in order to send rewards to you. Can you please send it in DM to me in Discord (ipaleka) or in Reddit chat (u/hopemeetme) after you opt-in for the ASA Stats Token (ASASTATS; ID 393537671)?
