### ISSUE TITLE
Folks Finance Liquid Governance Mint shows no longer minted funds

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#8]
by [@fredestante](https://twitter.com/fredestante) on [Twitter](https://twitter.com/fredestante/status/1516803277924581384):  
> The Lock&Earn seems accurate, but not the Liquid Governance Mint. 
> 
> It shows a balance that I no longer have commited/minted.

**Comment by ipaleka** [comment]
Mint functionality is temporarily set offline.

**Comment by AlgoRhythMatic** [comment]
Type: [B1]
Recipient: @fredestante (Twitter) - 100%
