### ISSUE TITLE
[F1+IC1+D1] Add Algoexplorer link to address for single address view

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#800]
By Maximus in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1152649878778937525):

> One feature I would find helpful. I like to look at the explorer for my wallet to see the most recent transactions. I'd like a link probably be good to have it right at the top just below the number address or turn the number address into a link to https://algoexplorer.io/ but for your address

**Comment by kerrilija** [comment]
Feature added, tested and awaiting for deployment.

**Comment by ipaleka** [comment]
> Feature added, tested and awaiting for deployment.

The same goes for the web version.

**Comment by AlgoRhythMatic** [comment]
@kerrilija - I came to check this one out based on reference in #788 - and am wondering should this already have "addressed" tag since it was closed as completed last week, or does that occur at some later date?

**Comment by kerrilija** [comment]
Yeah, the addressed label should've been added. Sorry, I was not aware/forgot that when I'm closing the issue, I should also be putting the addressed label.

**Comment by AlgoRhythMatic** [comment]
No worries at all!  My main goal is just to ensure you get rewards on time, and that no efforts go unnoticed :D
