### ISSUE TITLE
Remove ANS from initial checking for .algo name

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#818]
By kerrilija in [Discord](https://discordapp.com/channels/906917846754418770/973245314687434832/1164532658525720586)

<img src="https://github.com/asastats/channel/assets/49662536/8f1c68f9-11ad-4f0b-8a97-d8c816a3bae7" width="400">

**Comment by AlgoRhythMatic** [comment]
Hi there!  I see that this is tagged as a task.  From rewards POV, should this be considered like an AT or maybe an F?

**Comment by ipaleka** [comment]
> Hi there! I see that this is tagged as a task. From rewards POV, should this be considered like an AT or maybe an F?

Sorry, I forgot to label it, I guess a usual feature is enough as the work behind (for kerrilija) doesn't differ much from other feature requests.
