### ISSUE TITLE
[F1 + 3xF3] Missing icons and NFT collections thread

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#821]
[F1]

by Mocha in [Discord](https://discordapp.com/channels/906917846754418770/908054304332603402/1165393511466680320):

> Token logo request! $wMATIC from Wormhole https://algoexplorer.io/asset/891396362

**Comment by moloch10** [comment]
[F3]

These are collections that only have one naming set / convention:

SS72W76UMWTLMRLTYTA4JP7MV7Q7KEAPFG3YUX6DSJQ7IIALJGVUCMNHO4 - A. Rex Baby
5OOX7BJ5DWFNWZNUUPHKXGM6USJWKF4YSBLDK3SKHXWEBEDRXPHAX2D7CQ - Algoat
BVRSBJ6GVSDAXMF47PZ6FYM5MPHAUP67SCTTUGGIG2UTWEZCFWUU5AO77U - AlgoBeaver
HYFU2HFNVOTM43HYY4RLGPNSZQIXON7YYVZMGCX4LNHCX3TN2HKRHDZ4VY - Algogus
6XE5RJQR62FH3NPHMG2LVTC6U2VHY27WXBBQY3ILPD3IFFCVSBF6Y4PTXU - AlgoPUMPkin
HTQR3VGMRHJ2JK3KFJO4FG5XPWDB7A6KA42QKNG6JVKDO4HONJTMEDN23M - CryptoRaccoon
P5RA5P7HOAKP6PVAGTDAYSBGCQT7NWYR24AXULJKN5IWOB4SRDERNFDQPQ - Devious Dragon
5PEJFTTZVFKXOBQYGJFSPGTIKEXK6FVE5UA2DKOSA3J3VMZWSQKNSQXZDE - Freaky Creatures
744UAKDMJCJYVQSEJO2TWUN5AI6KLDGVCFN4XRMN43FPM35EGLB3DBTZYU - Little Bunny
JFUMAMF6XM44624AAA5JLELH7BIPMBPQI5O7SIR75WT2S3Y55OY6LFTGOE - OniSplashArt
LGCFH72RGTUUNLNZGHK3REDLR36BH4NIHBDRKCDE2TGRSCX64AQM3ELRAM - Pixel Genies
NBRBV5DZBOWJUSAFKV5SDOBJ4PZAKUVPGS3LWP5VMS7WKIEWKHADJWDAMA - The Algo Devil
XYYFHLOBMTGR5ZRFJUDKC5LXNHKD4SI7CJNUEJ7IMQLSRB7Z6MBJXYBVXE - The Algonauts
IDB47DKHOEK7IVWGQSOBISQJIEIJRCPFMJQDOH6FMFLX7VBAM5XQX5SSOY - UptownBully

**Comment by moloch10** [comment]
NAFE4FCBPAY2NWZ6ARV3NVLFKYGZDPL3YYS5QUVKB4KCMIOMEI2TKPIVMY - Mystical Mantis

**Comment by moloch10** [comment]
GQDZSNK5AVGUD2DG25NMYBNNWUPG4ZQGYZSKSB6CPAEHXM35OWN27MJM3E - Baby Ape

**Comment by moloch10** [comment]
[F3]

L7TNYRRBANYKFF2MAMCTOIDBHVJNGCTVYPAJXGKZ7N4OL3QPG6M525KTLA - AlgoBoy
QMZRNFXAFKYN27HUCX4TOK6VJ2RGIIEEWEURVOTODDF5HYXS57A4SQMBTI - AlgoCamello
XLQFNLIVP5DWI37LJ52SAK226IJXTSMZWA72XUIHBDDDJB5ZMRR56X6Z7U - AlgoCloud
WOJDZT2MKVOY2T4WLAEPFUC6DQLJ7L7OTNSL2PD5FQTWC3LUQV4PGNBY74 - AlgoDick
YYUFS7TIYPMPH5QLAYGVSTIGEM565LQANMXFPJAWJMLIT3NNWEO2ZKIOQQ - AlgoDino
BIGZHLYCGILASFMOIB5IXINNWN3NAQLBPEERNWTGELFNLZZDD2U5DKL6TE - AlgoKitty
7QLNCQPPL4WY4KP6MIYSXSCWKFJO2LDEZWPDCQZS3R5P4QKYHWDBAJII3Y - Algoroid
3AXR2Z2MB2NBDVXMBBTUYBQ6W4YUUCYF35EOGB6XLXZ6ADSRCKQNLWKDEA - AlgoSloth
IHCO5XRMY2FXGOA644ARSZ3TLVU76R77QK2SXZJNHWT4KRCVUGLEVBHJYY - CryptoKnight
IJHHYN5JNL6HFMGOBRBS5V47CNL6N6JT2ZJYGHHBB2GA5QP635PQWP546U - Gilbatar
DQLFHUFGEYE6OYDSAQYVXIN6TN7C2KLSTH7MLF3QLR7DDR3LC2PA6KDU2Q - KangarooFightClub
JXY2XR7FHY7IFUGTGVXBYCF4GNYGWZB5UGEXL57QSJ7NH5WXNO6KZJ4RWE - Lady'sHead
J6C6BCUEBG7SO33YDTFY2DTAFZLMZWDDPU2FSCTVLE5ZZNEQ47SDEMCYQ4 - Pixel People
YO52UCRXLGCIIQTIB64DMTY7HBEU5VIPX5V3JZT4YAF7BXX2NA7AIZ24MY - SkullCatz
7XPYBNGGHU53Y2SCUK62JRH7CWLAUWAOZ5SO6OULNLN2KSXLWPLSNTAFWY - TvGirlMadoka

**Comment by moloch10** [comment]
[F3]

A handful of these have as few as only two NFTs.

WRS2ZLH4P3FQTDHECC76L4UDPRGVCIPEPRS4EMJI7M3JXV744T6SBPOLFE - Abstract Rude
JQUI72E3IR44A24NKHFGAJNRI2EBT4K6GBU6YSYRBO3ILZUVFDRAEXCX34 - AIart
BFWNCBHPUVB5TEGPG45OR2UMR5LUVFGJHUNXBK5XWQT7HV2EN43QMIEEQE - AiredALGO
TNYEEC5JYYAGKUFTXZDKQ72VLXL3L4NKDD5QEVAV3WMF6BLTRV35YP7KSI - Alganime
CZI22OP6VGYGNGPZNFQT4W3SBQU5FWJZU7OIGJ5GY2IBLJA2N45ETNVMUU - ALGO Bob
MYZAPJRGGLCNQSKO3REUDHYTRXOATVCJFJYVFXM5SJM7QFR54K5YNYKQ2Q - Algo Creepy
7BUBURWB56M2EDG3XZV64JXPQEPJUXMZ7367GPLGE6BJXWX5ITZZPDZTHM - Algo Flat Cat
TBZDGSBUTJXWPJV6ISXPOB7YUENDTY2IOM4LLNFJVGYZ2HG7CC75ECW6P4 - Algo Inception
GARYNCOIUHQA5IPNF3QVDKJMQ2ZJF4EJSYN5FYOIFR65ZHUVLRTQ7VUNRQ - Algo Logo Pixel Art
DWJAMFDIN7FWHJTHZKNZA6UQHSRTMFF4Y7HJPRW7GJPHV2JR4YLTVZI5SQ - Algo Pengu
DCMF7SK5XTZUOJXAXDXIEZ2LBC4WMIBSJYZKOTHPZGQNEMX6HL74XL674Q - Algo Snake
BCC56GO7BLNFUANLVGLIYFFQ7OV7OBEPXHOZWG46GTYEMQXF7II7SXERXQ - Algo Solmate Bingo
LKQ5NR7VE3OHBMNZVTT4YFBEKH75OPZZFKD4PBBSBVBKCMKQNILZG6UKBM - Algo Toon
CQUQCW4I6IFQN2XGMONEUTHLD67WT22C6SADTIEQIMVYIEZ4EGOA4BG6AY - AlgO_Oso Panda
USVFPSQZ3Q42ZPD6KV4OLRRLMZYCADH3ZKW6YFKF2EU5SK6WRGSM7WA5U4 - ALGOATOR
SCULUDTJNB6N5OFZ7HRTRZRPUXKFC3F6YHWU7YPSHWDKLRDDBEQKZ55HFM - Algobeer
EONMAWNFKDEJI7HZ33EU77Q7P2YFDM4V2WKMXUNFIGRYLE2D7F6YZGEVT4 - Algobus
66QLQ6SRR55YBIT2TH6RBKN6NCH4UPM65IX2Z3H77SHSF42HWRDOZJRGDM - Algochan
M7UWJR4CREQISIGZFIUY6NKCQIQKT3HZ2P7YQHCECL5WAOKRRHIOGEBTQM - AlgoChest
7RTAGW3VJINHW57GQ4MKRLFRARCMZKCBNBDO4RKC7IPZWQP6EONV6U3ALQ - Algock
D6FC26U4PBWEY2CTDSTWCULGNRBDUT6EGYJOG4IYYQB4MRKIDJE4DJV7BA - AlgoCrab
2NKWGI3ZRVRX55ZCWWKHE6JI3P7M733OLIKIJN5O42UEIQ2XKL5OIAXGIE - Algodoptables
3ROEKAPGTN7BD5KYACJOL6QW6PEUAYLETOZYEKW3R3QY2XH2NBVQK43GFA - AlgoLeonSeries
KVQPL3WZUEA22B2EODQL6FQOLHOQQFK5MTODEED2EHICYQIZ66YIX75ZNU - Algopiggy
IGHZOQ4UZQ6JXYCWCH6LSBNXZ5OJBDDDSU3GF7UWBPXSIRWM23HTEWK6IY - AlgoPredator
SKSZ5JFON6VBJ2DBZBASJFPIOOSGCRWLKVWKGHEQ2Y57ESEEYDO5BS4UGQ - AlgoRacc
U7KL66XKO674XJ36RZ2IR5IN2ACSWQ23QUZN36ORZWUD7ME6HB34JJEYFM - Algorandians
VZRTRSTYP5BFCDGKN5OMDAZORIZVYXOOMIXFRG6R5ZQOXTMSNXSESFYKDU - AlgoShredderz
SLWH5QM4EG3VRXNXZPMH6SFD7IULZK7EKJPQD5MF2C3M67DWIEVWZ3LD7I - AlgoSkull
YBFHMGZDZPMKKN62XHATC4NMYGMHP7WNCSRUC5E5AGHTTNULB22QEFHVTE - AlgoSmush
JNXV7QIALNNZ245JJVGI4ILNEYTLMBWTQEWGF3JP7EQ3DMLXJHYVBV3UG4 - algowalk
J73EY7HH46SYOHAO5HYBLRTZK7NO25BFH7PPXJXEWD45VP5YDOMQS4SYIU - Alienism
2XL624DV4RPH2PW5Y5D2VOTEDU5TURV3DDO4KDUVRZGQUKGKN4XXL6SMUA - Alpaca Academy
LUXSKWJAXTVH7OC6BKUAFKGNHHZ7H4QXBFFX6KW26FLKBTGWEWNVUPTMQM - Bad Trip Toy
JN64CVZ75QDKIOHKKMIGI56Y632AXJJRAEGMDF2IDGDTEAOZG7BWYZK2LE - BearMan
EQC6MRCB2RVDQS4UEZ54DVWJDXCW4DTURSKCZH3QDQY4KP4I3PIELV5BHI - Beaver
KSXZ4BW3TMHGUKCODNBVFIKDQGX3E7ERJIC5PUJUE6SXESMOI2U5X3556Y - Beepboy: The Gathering
BLOCKIUINPDQQLE2SLJU6E32D4KV3TOCPEYXYBFYB3YEGS5TTTIV4SZCWM - BlockHead
22WBLCT5DBJNLGWB2KSLVXJUWLV7DHEA3IG4ON4J4DUYZLBRXM3USZLIJE - BlowfishGlitch
COMI2DK6UXMBQN7Z2SLMXS7YHMXGVIAOMFXF673CGN34RW3RH44EXOYCLM - Buzz Box
6IDXBZOAIOOBMHRWCWR3F2JPT3KJJ5ELOSTNMS6A5A4KPD5UW2YOSY5KGQ - Cat
CRUBNWGI2YND6HQGRTV2WYNX76PJRWZGMJ652EKGZROMV7CZVHSFLCMW34 - Crubyk
4RFJ7QMASMLQ2M7YGW7LFBZK254FSEJQACWDEKAJDATCBY723ONQ4CYQCY - CryptoCyclo
OV76CD2H3HXBLSGJUCOWQGASV47EELLAJMD2KNIO72NGNOOKTF7DLZGJUQ - Depressed
2ZSQTWJU7BIXOC74N2L5NELYTR36QUH5MXY2BY7BVVDNFWSISOGGPKWGLI - Electrical Creature
GO3PCJK6UQUKWF3I775S63Z5KN2CP5XXCWR6S4RFJ6BH5U2YE5XMYXZDPU - Etherborg
6VBSRJLOEAJNJH5PEI6HQ543OWNZPGMGDNPELXDXXZX63TDYWMKP7NG2GA - FFC Key
EGWR6OWC464JKFZQZBVC5PMREGVHIXIHB6HEWKO3PGMDM4CNK43VJLAXOE - Flower Pot
MJVJOKNPFDUIOORKJOYL3GEMZNXKBBKRTA6X3XM2U65FPIGVC36LI5STJM - Garlic
QP6ANA3YUVT7VV2IRZJ3KUMYC4NQHOC7DR47C3VYGCEGSE4OKKPMHXSN2E - Ghost Squad
QWIU2LHXTPKUO3FTVRYE2RGNAMBWTRYSDH5BGSZHPYPZ3ZAO6HJ4HIIA34 - Golden Bug
5CV3FJAKCKJ7IV2GPZNEZ2CODLX6CKGNUXE4JNMOR7GBSWJ72YOLW3XXK4 - Hoodie
3MJ5M6IG7HZ7CQNSMF4KCSYINLSF3S4R5PIKN2AJW74VDXWSJA2L6BTGOE - HoodieGang
IKARTXU76KSJNN76C3BOJRMJGKC6KIQT6WMMDJYW64F4IBRHKW6EBAIMGY - IKO x VR
5S5T7FCQCTDLGJSQQUUL26RBWL2VIKDAOIAD6O4MPO62FJ2EQKZEVNAAJQ - LalaCats
G3YM7AW2RKPFBNE5UIICAMMNHRUQ65W27F4ED2AK4NMARLFHXLGGK3X66Y - Leaping Leopards
44ZCCYKK2YSVFMREFCANMPHS3GBBJR7QM3HOP4EIVPQJTK3Q7L3ZKBE7AU - Lobby Sheep
35U44LKZ4HPXPPDS65DIPBKFGHG6LRYWKDB7V4SYP6S7QVVJHBPI7AYSYQ - Loving Lemur
F6M5GWFN42PQPHKKNINIXTYSMIIXT7SODHLEJACXHQDFZ77ILFUDCPAYNU - L.V. Gems
6TOUUDE5CCTXY44VTKY5X2N7V4LQZJKNHDQJECBQL2CSV6LCWR5BAHYWUA - Meow
2FDU3BUX64JCFI7JCZOSI3QHZ2NCMAWQEEWGFYJ43AYHX44A327DCAPGTA - Mini Munster
6NKK77TQN7SJSQY66QGR2WLEQRTVUYOB3NXNKJRFELOCNFKB6METGTNMVE - Mutant_Nfts_Ape
FZN6BRO2AVZYU2I6GBME7TQPBNZTQUZBYF5VX3BJ7RCFIYDVEIH65FJ2XU - Night Monkey
JGFXTXJOWDNHVZHWP2ONL6JCZC4P6RWOYXUAULXCITEED2LTUL6ZQPKXSE - No Crypto-Weakness
DOFCOGEHZMSC7553ISLPYUIZNDKOWFJ3QU2KHIPGE3VDCJ7C3EWFC5VCHQ - OGsloth
GOALJZLQXLBOTYI6MPODEF5EHO7U5QDBSCOX44LEY535Y5RJVDYZQ4BNQ4 - Oink Soccer Teams
SVHR3COXIW2QEODUHROXTGMQ6UHN4AWCJ75PMILZZOKJMTC3Q2XER4PQIQ - Pixel Bot
EQO36N3SINLNJGMXDTNHWEKFHZVVTOO5EELZNOACDWYP4VZZ5UDFP6V2UM - Pixel Mouse
2YGJONT2KVSAVLPWAUNA4ALPDSNOIGQNALKWLZRI2ASAGGY7BESWZNTR2A - Pixel Piggy
H644V57AI5JTRRSYR6SDOMP2IQYM74PLXYXABGBPTCD47RMOQNTAXQB7QE - PlantAlgo
QEKFA5YGVXZXUDIJOMPMRIBQHSX3V4WZGKEX7GK4MXC7YFBFUTRKE6J2JM - Punk Kid Crypto
DZYZBA7Q6OB2XEQNX4KLWMREB66AEEFPM5ZJX27QCVYFYHPAYACHMLL2V4 - Punk Tortoise
OPZ3D5UV3FQ5D4HMX7B46OA2PS47IPLKZT4IXJEHHX6FMU6MQBPTOBZJ2U - Rebirth: Pixel Inu
5GJIWCKXYJE26L23BIQSBOBCDDN4TEOWIGXHEFJETCCIOXKVQAZCSDBRKU - Scoby The Cat
CI25DYUPH5LCG3LOZ24GPQE3SU7K5AVAUEEXVUE7TCPCCL2LQJULTGHFVA - Secret Society
AFRYCV7VQIQEHYIQBYUEDU4WRBJCKXX57JCTF3RDGCU4V3MRBAX2PJUYM4 - ShininGirl
K2QNA6O3KIQSL4UXRBBFRATA3H5R3BTALKWCVUBL7L5GUL6SLX3LUAXV74 - Sia Furler
7NTYOTTEINQO5BWJBAL4TGQLMXKVAB3N324HLFULY3NABOMVATYUNC6PGU - Space Monkey
54KTMHEHLHYO5AAEHLJBNGZZIOXSQA4DQUNU7GYEPZBVZWA6GS7M3UAFRU - Subject No
IFJO3XJEYQDACQTCAGP22YAP3XALVW7NT6VQ2XG22E5XBQEHCLRBJR7QA4 - Super Shroom
3OCRP2LVPS2HR54EGLCNF63L56QRGNZITUSFYZX6DPU7PMGJ2KWLDLPRG4 - The Smoke Punks
5EK6XQD7S44YRT7IV4DJIUPQ4E76SCP3L4FUVFFR4I4ANX4NGPZR3FQ3T4 - Tiger
WOUKFF2L4LXFO4AA2LL3X6IXOUYFD3MO2M5RVQFAQ76T22FOYGXJWNAHM4 - Tiki
PY3SYPLQYQWGTYBDEKEANUDOSLG5TTKS3FN43UJU3FZJX2ESPORUHXSZUY - TrippyMushAlgo
3RQFOOFJDLUM2XL7HQ5KUPOFAYFZRIF42NPF6SVTY57WRJVH3FWBGKMEXU - TwentyFeelings - Haniwa
FF6ZFKQWOZNGUGXFKOBH5WFAPY6SWSLKIIW52G64CQUKZWU52TN3BNMJPU - Twine Early Access Pass
2U2C56YTOMM6B226QEJMFUI2VF7WRANBPN5XPJCZTWCHE3UEWRK6M6N4XI - Unknown Heads
J4GDBWWX53CQGIVV5HC663NAPH3LI4KN7ZC4IVA7M3SGWVSEYDOUMWPWRY - Waifu
KNYVSLVHLLKKMELHBZZCEP5OCY36EGM7BYTFYX4U7TV5SEY67IL4FTXMUE - Z-Munster

**Comment by ipaleka** [comment]
New thread: https://github.com/asastats/channel/issues/843

**Comment by AlgoRhythMatic** [comment]
So just to be sure I have this correct, this should be entered as:
- 1 x F1 entry for Mocha 
- 3 x F3 entries for moloch10

**Comment by ipaleka** [comment]
> So just to be sure I have this correct, this should be entered as:
> 
>     * 1 x F1 entry for Mocha
> 
>     * 3 x F3 entries for moloch10

That's right! :)
