### ISSUE TITLE
Some Rand listings aren't shown under Stats at all

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#823]
Some listings I have on Rand aren't displayed on my portfolio. I suspected it might have to do with changing the price of something already listed but even after the removal and fresh listing, it's still missing. 

Asset ids sent to ipaleka via discord DM.

**Comment by ipaleka** [comment]
I'm not sure what causes these tbh. The listings are being fetched, but it's been a slow process to update since the last time - around halfway through after 16 hours. After it finishes, the cache will be updated.

The deployment is expected to happen tomorrow.
