### ISSUE TITLE
[F1+IC1+F1+F1] Swap quotes for mALGO on Pact UI are not correct

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#826]
ASA Stats displays a higher value for mALGO open market swap than it actually is on Pact UI.

<img src="https://github.com/asastats/channel/assets/82002056/df01b765-e1e8-41a9-a870-e235fcf0c6b6)" width=400>

<img src="https://github.com/asastats/channel/assets/82002056/d5640a77-012b-407a-85e9-6e0674f7767f)" width=400>

**Comment by ipaleka** [comment]
From https://github.com/asastats/channel/issues/806:
> As mAlgo AMM liquidity has increased (and also we've deployed a bugfix), we're going to close this and redirect rewards to https://github.com/asastats/channel/issues/826.


By Mocha in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1160669721922916365):

> Random but $mALGO is supposed to be redeemable on Messina 1:1 to $Algo so shouldn't it be the same price? Or more after the Governance periods end because of the addition of rewards... 
> Right now it's showing as significantly less which is I guess including price impact from swapping on the open market

-----

By Maximus in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1161424978235899944):

> https://messina.one/ Malgo doesn't show up correctly. 1000 Algos shows up as worth like 360. Currently it's suppoed to be 1-1 Algo and in the future it's suppoed to be worth more then 1 Algo each
