### ISSUE TITLE
Include a copy [to clipboard] icon next to ASA Ids

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#83]
Similar to how Algoexplorer and other dapps have a copy icon next to a wallet address, it would be great to have the same with asset Ids. 

![image](https://user-images.githubusercontent.com/97535612/169123464-f1dcf5e8-123b-4f53-98ae-fcc7041ea3b6.png)

**Comment by moloch10** [comment]
Rather than the word COPY, can you make it an icon?  😅
HTML code: `&#128203;` renders what's in the screenshot, no image needed. 

![image](https://user-images.githubusercontent.com/97535612/171179445-d015fbfc-98ab-4fae-952f-a5fb7c2bba01.png)

It's noticeable with NFTs but when viewing ASAs especially, the COPY is kind of lost in the sea of text. I feel an icon will help break up the text and jump out as an "action."

**Comment by ipaleka** [comment]
> Rather than the word COPY, can you make it an icon? sweat_smile
> HTML code: `&#128203;` renders what's in the screenshot, no image needed.

Deployed, thanks! :)
