### ISSUE TITLE
goUSD LP on Pact displayed wrong

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#836]
By venture.algo on [Twitter](https://twitter.com/venturetk/status/1721277747371081998?t=n4_1zMcKEJE5AolK3pZGHg&s=19):

> Odd, @asastatscom seems to be misreading the contents of my pact LPs. goUSD in particular.

**Comment by kerrilija** [comment]
By venture.algo:

> Tried to comment there but it wont let me, so:
> 
> For my gousd-xusd pact LP, asastats is reporting ~17% fewer gousd than I can burn those lp tokens for. The xusd half is roughly accurate however. I hope I have not misread something.

**Comment by ipaleka** [comment]
Yep, this is probably the same error as with other assets,

**Comment by ipaleka** [comment]
This problem is resolved in practice as the proxy pools functionality is temporarily removed. Proxy pools functionality need a redesign.
