### ISSUE TITLE
[F2] Research and implement Alammex/Compx farms

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#838]
By Mocha in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1171712371845255178):

> https://twitter.com/Compxlabs/status/1722124996322152839?t=liiB8sJ19YquOyMwKXgkBg&s=19
> New auto-compounding farms!!! Idk how hard this will be to implement 😅

-----

https://app.compx.io/farms

**Comment by AlgoRhythMatic** [comment]
What do you think this should be in terms of Feature Request vs. followup research?  Like F2 or higher?

**Comment by ipaleka** [comment]
> What do you think this should be in terms of Feature Request vs. followup research? Like F2 or higher?

Yes, I set it to F2 as request + followup research. Thanks for pointing out this. :)
