### ISSUE TITLE
Bulk listings on AxN don't show up under Stats

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#841]
While looking for NFTs, I stumbled on this address:
algoknight.algo / GV6MAOPPFLZFB2LHR44EJK4MIZDPGC2DZ5CFFUOOWTPU3BI74PT5KKJ5C4

Stats only shows the single mint items. Checking AxN will show the singles and the multi, the Pera governance lot. 

https://www.asastats.com/GV6MAOPPFLZFB2LHR44EJK4MIZDPGC2DZ5CFFUOOWTPU3BI74PT5KKJ5C4

https://algoxnft.com/address/GV6MAOPPFLZFB2LHR44EJK4MIZDPGC2DZ5CFFUOOWTPU3BI74PT5KKJ5C4?tab=buy_now

**Comment by ipaleka** [comment]
Deployed, tho we don't have yet a mechanism to show those multiple non-1/1 listings.
