### ISSUE TITLE
Mobile app shows wrong asset icon sometimes

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#842]
The icons for ALC (445905873) and AGOLD (877703456) are incorrect.

![image](https://github.com/asastats/channel/assets/97535612/17c0bccb-bf65-41fa-80fc-57aede67a09e)

They updated their icons 8 and 10 months ago respectively.

https://github.com/tinymanorg/asa-list/tree/review/assets/ALC-445905873
https://github.com/tinymanorg/asa-list/tree/review/assets/AGOLD-877703456

**Comment by kerrilija** [comment]
I guess that will require clearing the cache in Android settings.

Settings>Apps>ASA Stats Mobile>Storage>Clear cache.

It will most likely delete your saved addresses too, so be careful.

EDIT:

Here's what it looks like on my end:

![Screenshot_20231113_225810.jpg](https://github.com/asastats/channel/assets/82002056/38e1aeef-5a44-43f8-bae5-6f9c21f87b42)

![Screenshot_20231113_225714.jpg](https://github.com/asastats/channel/assets/82002056/484c4759-9759-40fa-bc75-af1e1ac618f5)

**Comment by ipaleka** [comment]
@moloch10 can you confirm that kerrilija's suggestion resolves this so we can close this as `wontfix`?

If this is sort of an issue, we can maybe add a feature dependable of user settings (both for the mobile app and website), for *manually* deleting the icons cache for the user?

**Comment by kerrilija** [comment]
Yes, that, or to force cache cleaning on app update. Got to see if it's possible + addresses history must not be deleted.

**Comment by ipaleka** [comment]
> Yes, that, or to force cache cleaning on app update. Got to see if it's possible + addresses history must not be deleted.

Dunno, a button click in the settings sounds to me like the best option, I don't like doing things *behind users' backs*.

**Comment by moloch10** [comment]
> I guess that will require clearing the cache in Android settings.
> 
> Settings>Apps>ASA Stats Mobile>Storage>Clear cache.
> 
> It will most likely delete your saved addresses too, so be careful.
> 

After following these instructions, the correct icons show up.

I looked for a clear cache option in the app itself but didn't think to go to the system level.

I like both suggestions to clear on update or to have a clear button in the settings; whatever's easier.

**Comment by ipaleka** [comment]
Request dependable on user settings added. https://github.com/asastats/channel/wiki/FeaturesDependentOnUserSettings#clear-cache-button
