### ISSUE TITLE
[F2+F2+F1+F1] Missing icons and NFT collections thread

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#843]
A new monthly thread; add the updates as comments.

**Comment by Algoworm** [comment]
Polkgold....Inu Moo.....AIINU......GAS ......missing icons

**Comment by ipaleka** [comment]
> Polkgold....GAS

I'll need IDs for these two.

> AIINU

Is this  https://algoexplorer.io/asset/1024916561 ?

**Comment by Algoworm** [comment]
Polkgold...ID:1237529510
Inu moo....ID:507472097

**Comment by ipaleka** [comment]
I'll need IDs for GAS and AIINU.

**Comment by Algoworm** [comment]
[F2]

GAS...ID:1144340594
AIINU....ID:1024922832

Two more
GOLD....1241944285
GoldDAO...,1241945177

**Comment by Algoworm** [comment]
LOTTOR......1217302022

**Comment by moloch10** [comment]
[F2]

4GSBNCVJRGYIQLT3IEWVUVHDQ5N2PIEYSBUJ2LCJZAPJ3CBQCAVZ474J24 - Algoficial Intelligence
N54Q5UWFLMTQ6DKTIU3GPC52HJMJ3VMREBS7UCWHDUILHZ3XR4IA52UGUY - AlgoInvader
L4LEFXZM4V5CDU7HSWKOQS6Y3AQ5FQX3JU6YU2HKOTOO3ELNFHZXTAYV4A - Algomelon
KXI5KF43DN6VLUHL2RS4PBN3CF2EY5UBWWQR4WVLXP6DKA26A2E2KCZAJE - Algorandoms
NAIJ64IBC44SOZ45JMVMSBAXV35YLR7EVXEOB4XDUUUKIC7S5ZVADTRJUQ - AlgoStonerClub
DY4FJJINND4U6UDJGMX6VNHCABJMJCSNWIACHXLPQFKOBXLSVOKKWNGORE - Crypto Dragon
NESTZHPAR2M4JSAUXKXYF5FXTC5VGMXIYXH2UZ2P3LIDULTWHGFE2C6B3M - Dralgo
PBLXJ5QEX22RJSZEFLSL766MFQ6ZYI235VYDO4NYPUGRSYULCSG3KA7ZNI - Elric
JOURMYWUIJEZOEZ3L4FC72ZILQSYUKJVJSRHGXM3FIAIWN4RMBBNKAXW4M - Mission Journal
AEDAHEO5X7CUBW6IPWPRTNAEHSICKRXRMTSOZFEXDGFHJUFVRSCYVEZVNE - NXTG3NZ 7220
AEG367HVTPAOYKQP22YWC5HSELQYYYPIS3ETU4BUQGMXTSPOBIVTOSETCA - Pixel Plankton
YE6MJYNERM2742UGWGPQS7KTJ5UJS33X33R6FDPAG6T3SHSM4R5XEIC4PU - Pixel Weapons
YEJNGFJVDWMXO7ZGHSXZSDYBNZXPQVMEGLKNMHJO2BRPYMQI3SNTFXX4XE - Poop Knife
TUO32CEMANLZ5KWEJB5HFLRVXBMK7P6YBMH5CPKHOZZQCXQP23EGBOOZTI - Torii
N7HAIZ7VQLMPO55TXFOVOZTKESJOLLFOUOAXFWWLVNFDCX45KSJZDV6EPU - WOM4N
AJ2XI7ESJF5VVAZQRHMW4A56ZLIRH4SSDFKVWCBA6DXBMQBINIZKXBKYQU - Zest

**Comment by moloch10** [comment]
NIKO - 1265975021

**Comment by ipaleka** [comment]
> 1265975021

The domain has expired or not been set up yet (rxelms.com), while Pera's page brings something that looks like a generic icon (https://explorer.perawallet.app/assets/1265975021).

Any other source?

**Comment by moloch10** [comment]
> > 1265975021
> 
> The domain has expired or not been set up yet (rxelms.com), while Pera's page brings something that looks like a generic icon (https://explorer.perawallet.app/assets/1265975021).
> 
> Any other source?

I checked the handful of places I know too but thought you might have something else. 🤷‍♂️ I asked in their Discord but haven't gotten a response yet. I guess placeholder until then.

**Comment by ipaleka** [comment]
[F1]

By Mocha in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1189658704694485214):

> GM, logo request for $BARB 🙏🏾 😁 https://explorer.perawallet.app/assets/1285225688/

**Comment by kerrilija** [comment]
[F1]

Unit name: ORA
ID: 1284444444

**Comment by moloch10** [comment]
> > 1265975021
> 
> The domain has expired or not been set up yet (rxelms.com), while Pera's page brings something that looks like a generic icon (https://explorer.perawallet.app/assets/1265975021).
> 
> Any other source?

Hey, I noticed their icon has been updated:
https://allo.info/asset/1265975021/token
https://vestige.fi/asset/1265975021

**Comment by AlgoRhythMatic** [comment]
I added Algoworm [F2], moloch [F2+F1], and kerrilija [F1]. Is this correct? Should this now be finalized as archived?

**Comment by AlgoRhythMatic** [comment]
Updated to Algoworm [F2], moloch [F2], Mocha [F1], and kerrilija [F1].
