### ISSUE TITLE
Pepe 2.0 ASA 1137071163

### ISSUE THREAD

**Issue by Blueflash19** [asastats/channel#844]
Bug description:
Pricing info is wrong.  On Ethereum $1 would purchase circa 24.6M Pepe 2.0.

![image](https://github.com/asastats/channel/assets/150914931/cdc31ac8-c09a-4b15-8ad5-042b8089ef7b)

On Algorand $1 would purchase circa 68.3M Pepe 2.0

![image](https://github.com/asastats/channel/assets/150914931/5e2cd2f1-2042-45cf-86c4-0393585db02b)

This is problematic when setting up a liquidity pool.

**Comment by ipaleka** [comment]
I checked two random holder accounts:

<img src="https://github.com/asastats/channel/assets/49662536/7ef30b17-dea5-4cca-a73b-47e842bf954b" width=400>
<img src="https://github.com/asastats/channel/assets/49662536/d2942551-84c4-4bc6-ab7d-8d20e22779b6" width=400>
<img src="https://github.com/asastats/channel/assets/49662536/14bdee1f-87ea-435b-963e-4f52f9c7e44d" width=400>
<img src="https://github.com/asastats/channel/assets/49662536/b80bdeec-d409-467c-abbe-a955f0954b9b" width=400>

Those results are correct on our side and they imply (as one of those is a whale) that only one pool in the ecosystem (Tinyman's) provides liquidity for Pepe 2.0.

And basically, that's the only thing ASA Stats takes care about. It's up to the ecosystem's *players* to provide liquidity and we are dedicated to correctly showing the values of our ecosystem only.

P.S. Our job is to show how much value our users can get for their tokens, while our user widgets (planned for development in the following months)  will allow to swap them all in *one* click.

**Comment by Blueflash19** [comment]
When I tried to add liquidity to the Tinyman2 pool, by adding 13Bn of it, that had absolutely no impact on the exchange rate.  Why would anyone bother to provide liquidity to Pepe 2.0 if that means exchanging it for third of its value compared with Ethereum?

**Comment by ipaleka** [comment]
I'm adding  `wontfix` label here as there's no related bug in ASA Stats. 

You have to understand that those two assets aren't the same and that is true for any example between blockchains. Even stable assets aren't the same and the only thing that makes people act as if they are the same is the fact that some entity has provided a bunch of fiat currency/assets to keep them stable and equal.

In this case, nobody can confirm that this asset you refer to isn't fake and created just to make a rug pull - and that's one of the reasons why its price doesn't "fit".

**Comment by Blueflash19** [comment]
It’s not fake because it can be bridged back and forth on Messina, and has the verified tick.  Is the same Pepe 2.0 that’s listed on Coinbase, just wrapped, I’ve bridged some over myself

**Comment by ipaleka** [comment]
> It’s not fake because it can be bridged back and forth on Messina, and has the verified tick. 

Oh, sry, I didn't check before entering the discussion. I guess this changes things and we'd probably need to implement some custom exchange functionality like we didn't here: https://github.com/asastats/channel/issues/806

**Comment by ipaleka** [comment]
> It’s not fake because it can be bridged back and forth on Messina, and has the verified tick.  Is the same Pepe 2.0 that’s listed on Coinbase, just wrapped, I’ve bridged some over myself

https://github.com/asastats/channel/discussions/845

**Comment by Blueflash19** [comment]
Hi,Any progress on this?

**Comment by ipaleka** [comment]
Nobody has provided any idea in that discussion... #845 

Do you have any? From where in our blockchain we can fetch the actual price?

**Comment by Blueflash19** [comment]
I would suggest CoinMarketCap.

**Comment by ipaleka** [comment]
I'm afraid you didn't understand the problem. We are an Algorand blockchain portfolio tracker and we show the values users can get by exchanging their assets in our blockchain.

The main goal is to create a user widget with a button "Sell all" and in a few rounds that account would be filled only with Algo.

**Comment by ipaleka** [comment]
Please continue in the related discussion thread: #845
