### ISSUE TITLE
First pie chart not adding up to 100%

### ISSUE THREAD

**Issue by moloch10** [asastats/channel#86]
While browsing an address' NFTs, I noticed the following: 

![image](https://user-images.githubusercontent.com/97535612/169553812-e62ea808-86f5-47f5-aa76-4932db408001.png)

I suspect it might be happening because the overall value of NFTs is greater than the assets?

This isn't my wallet but I can DM you the address if needed.

**Comment by ipaleka** [comment]
This is a deliberatley chosen behavior for the Alpha version. We could either completely ignore the NFT evaluation (like in total) or make it visible in the chart.

**Comment by moloch10** [comment]
> This is a deliberately chosen behavior for the Alpha version. We could either completely ignore the NFT evaluation (like in total) or make it visible in the chart.

Hmm not sure I understand. Since there's a sliver, some value had to be used to make it look that way? 
The NFT portion looks like 96% and the ALGO section 4%. It seems like the titles are off.

**Comment by ipaleka** [comment]
> Hmm not sure I understand. Since there's a sliver, some value had to be used to make it look that way?
> The NFT portion looks like 96% and the ALGO section 4%. It seems like the titles are off.

Kind of, it would take too much time **just to fix that labeling** from 1,090.98+96.89 to 100% just to fix those numbers, while Algo slice will stay the same size (around 8% or `96.89/(1,090.98+96.89)`).
 
> I see you won't fix it, I'm not "fighting" for this, it seems like just a mislabeling issue though.

Yes, it is indeed a bug, but in Alpha, it will be automatically fixed in Beta when NFTs get the values.
