### ISSUE TITLE
Post Algostake announcement on Twitter after ASASTATS-ASASTATS program is deployed

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#87]
https://github.com/asastats/channel/discussions/60#discussioncomment-2792694

- Take screenshot of ASASTATS pool on Algostake to share on announcement channels.

- - - - -

You ask we listen. Staking rewards go live @algo_stake.

Stake your ASASTATS and earn ASASTATS
[App.algostake.org](http://app.algostake.org/)

#asastats #Algorand #algofam

- Attach photo

- - - - -

**Comment by AlgoRhythMatic** [comment]
I signed up for the Reddit post, so am happy to do this one two (unless someone was already planning to).

**Comment by AlgoRhythMatic** [comment]
Sorry for the initial misfire.  2nd attempt w/ @SCN9A's image looks much better!
https://twitter.com/asastatscom/status/1527753313415884802
