### ISSUE TITLE
Post Algostake announcement on Reddit after ASASTATS-ASASTATS program is deployed

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#88]
https://github.com/asastats/channel/discussions/60#discussioncomment-2792694

Title: ASA Stats token staking is live on Algostake
Subject
We are excited to announce our staking rewards program is live on Algostake.

Stake your ASASTATS and earn ASASTATS
[App.algostake.org](http://app.algostake.org/)

- Attach photo

**Comment by AlgoRhythMatic** [comment]
Done!  https://www.reddit.com/r/asastats/comments/uu7hh6/asa_stats_token_staking_is_live_on_algostake/

**Comment by ipaleka** [comment]
By AlgoRhythMatic on [Reddit](https://www.reddit.com/r/asastats/comments/uu7hh6/asa_stats_token_staking_is_live_on_algostake/).
