### ISSUE TITLE
Post Algostake announcement on Algostake & Algonaut Official discord after ASASTATS-ASASTATS program is deployed

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#89]
https://github.com/asastats/channel/discussions/60#discussioncomment-2792694

- - - - -

We are excited to announce our staking rewards go live on Algostake. Stake your ASASTATS and earn ASASTATS on http://app.algostake.org/

ASA Stats evaluates and presents ASA and NFT price information on the Algorand blockchain. Portfolio Tracker, API, and Feature-Driven Development. Check it out https://www.asastats.com/. An explainer video of the ASA Stats portfolio tracker is available on https://youtu.be/M8_dWMNWmCo

- Attach photo

- - - - -

**Comment by Motuwagon** [comment]
I was definitely going to bring it up over at Algonaut official.  I can copy paste any official announcement in their Asa Stats channel, and their Algostake channel. Is the above the official statement less a photo.   When is the launch of the Algostake pool.

I am not regularly on the Algostake discord, jumping in to announce a new pool would be better from one of their regulars.

**Comment by ipaleka** [comment]
> Is the above the official statement less a photo?

Yes.

> When is the launch on the Algostake pool?

In 15 minutes.

**Comment by Motuwagon** [comment]
Ok will do.

**Comment by ipaleka** [comment]
<img width="1021" alt="169605842-c9051397-ae09-4cd1-9b70-d443c180401b" src="https://user-images.githubusercontent.com/49662536/169606410-603d7d57-51c5-4a68-a593-3373874fc35f.png">

or

<img width="510" alt="algostake1" src="https://user-images.githubusercontent.com/49662536/169606416-d195fb34-52b1-49f1-a346-22569713cca9.png">

**Comment by ipaleka** [comment]
May I close this one, did we post in Algostake's Discord?

**Comment by SCN9A** [comment]
> May I close this one, did we post in Algostake's Discord?

Algostake announced the pool in their announcements channel 

"@everyone https://www.reddit.com/r/AlgoStake/comments/uu7nn7/algostake_update_520_new_customer_and_new_pro_pool/?utm_source=share&utm_medium=ios_app&utm_name=iossmf"

There are featured channels for projects staking with Algostake but not for ASA Stats. I will contact Algostake on discord and ask about criteria of there sub-channels.

**Comment by ipaleka** [comment]
> > May I close this one, did we post in Algostake's Discord?
> 
> Algostake announced the pool in their announcements channel
> 
> "@everyone https://www.reddit.com/r/AlgoStake/comments/uu7nn7/algostake_update_520_new_customer_and_new_pro_pool/?utm_source=share&utm_medium=ios_app&utm_name=iossmf"

Ok then, IMO that covers that part of the issue.

> There are featured channels for projects staking with Algostake but not for ASA Stats. I will contact Algostake on discord and ask about criteria of there sub-channels.

If we can't provide enough *movement* and news in their Discord then that can become counterproductive. I'd rather to not create one before we design our marketing campaign and it outcomes with a suggestion for that.
