### ISSUE TITLE
[F1+F1+AT1] Replace AlgoExplorer links with another provider

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#893]
By SCN9A in [Discord](https://discord.com/channels/906917846754418770/973245314687434832/1187494872459005952):

> https://x.com/alloinfo/status/1737906298568483282?s=46&t=Oo_OnKYsslLjZ1XSqGWTHw
> https://x.com/johnalanwoods/status/1737937586172076514?s=46&t=Oo_OnKYsslLjZ1XSqGWTHw
> AlgoExplorer would shutdown

-----

By Mocha in [Discord](https://discord.com/channels/906917846754418770/915342738201931836/1187787395257610240):

> Does this help? 
> <img src="https://github.com/asastats/channel/assets/49662536/ea4afbbe-4eac-4aff-93f4-162731f5e4eb" width=350>

-----

~~If nothing changes, we're going to set https://app.dappflow.org/explorer/home links next week.~~

**Comment by kerrilija** [comment]
This will also require updating links when clicking on an address.

**Comment by ipaleka** [comment]
> This will also require updating links when clicking on an address.

Yep, so:

1) asset pages
2) address pages
3) group transactions pages

**Comment by ipaleka** [comment]
> If nothing changes, we're going to set https://app.dappflow.org/explorer/home links next week.

https://allo.info is live now, so we'll use it instead.

**Comment by ipaleka** [comment]
>     3. group transactions pages

Neither allo.info nor app.dappflow.org index groups (atomic transactions' IDs), so we'd probably need to fetch transactions' IDs and replace all the NFTs purchases group records with them, like `https://allo.info/tx/{tx_id}/group/`.

**Comment by ipaleka** [comment]
For now, we'll just leave the group transactions as is, to point on AlgoExplorer...

**Comment by ipaleka** [comment]
Website links have been changed, all but NFT purchases' links whose target remains to be algoexplorer.io/tx/group/...

We're expecting a response from allo.info about their plans to implement group IDs in links and we'll act afterwards.

**Comment by kerrilija** [comment]
> AlgoExplorer will be shutting down on the **31st January.** This additional time will let @AlgoFoundation to change exchange links.
We have always tried to do out best to bring the best UX and not just showing blocks and transactions. We wish the best for 2024.

[Tweet link](https://twitter.com/algo_explorer/status/1742183575208788247?t=I6rPDB4Kuf_ki0TAZvmoig&s=19)

**Comment by ipaleka** [comment]
*This additional time will let @asastatscom to change NFT purchase links.*

:)

**Comment by ipaleka** [comment]
> > ```
> > 3. group transactions pages
> > ```
> 
> Neither allo.info nor app.dappflow.org index groups (atomic transactions' IDs), so we'd probably need to fetch transactions' IDs and replace all the NFTs purchases group records with them, like `https://allo.info/tx/{tx_id}/group/`.

Well, this was pretty fast:

https://allo.info/tx/group/TicS8DUbqkCMptUSHk3xqd%2FDrfcdiULcKqq9A56sHkk%3D

Implemented on the website.

**Comment by kerrilija** [comment]
[AT1]

> Implemented on the website.

Also updated in the mobile app, awaiting deployment.

**Comment by kerrilija** [comment]
Due to the simplicity of updating this feature in the mobile app, I feel [D1] would not be fair in this case. Therefore, I suggest [AT1]. Latest mobile app builds are live on the stores, so this can be closed as completed.
