### ISSUE TITLE
Text instead of URL for ASA URL is not handled

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#916]
This is an invalid link:

<img width="593" alt="image" src="https://github.com/asastats/channel/assets/82002056/eff6ab05-394f-46ed-b94c-951febf7362d">

**Comment by ipaleka** [comment]
As this had happened only in non-eval section, and to avoid additional checks (and so increase rendering time and demand for resources without a practical need), it is resolved by leaving URL characteristic, but without opening a window after a click.
