### ISSUE TITLE
Add Cometa's phntm staking program

### ISSUE THREAD

**Issue by kerrilija** [asastats/channel#924]
Feature link:

http://app.cometa.farm/stake

**Comment by ipaleka** [comment]
Announced, but still not on Cometa.

**Comment by kerrilija** [comment]
> Announced, but still not on Cometa.

<img src="https://github.com/asastats/channel/assets/82002056/14b6e220-8b77-470e-93a9-0dba2d8280b3" width=300>

Showed up in their UI now.
