### ISSUE TITLE
[B1+B1] Fix dark theme issue in Features and Subscriptions pages

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#941]
[B1] SCN9A 
[B1] kerrilija

-----

By SCN9A in Discord DM.

**Comment by kerrilija** [comment]
<img src="https://github.com/asastats/channel/assets/82002056/eca8a8e5-2c4b-4024-b8e2-9356fd8357d8" width="200">

In mobile view, tab containers width should be defined by text width
