### ISSUE TITLE
Add Cometa's PURR-PURR staking program

### ISSUE THREAD

**Issue by Algoworm** [asastats/channel#963]
Feature link:app.cometa.farm

**Comment by ipaleka** [comment]
As announced in https://github.com/asastats/channel/discussions/130, we won't need any more dedicated issues for existing providers' new dApps - we run a script a few times daily that checks all the providers.

We'll reward activity where you ping us in the dedicated monthly thread, [here's the one for this cycle](https://github.com/asastats/channel/issues/955).

So please in future, just create a comment in the dedicated thread and we'll run the script asap.

In a case like this
