### ISSUE TITLE
Monthly update thread - ASA icons, NFT collections, new dApps from existing providers

### ISSUE THREAD

**Issue by ipaleka** [asastats/channel#967]
[F2] @moloch10
[F2] mochanerd
[F2] @Grinnmarr
[F1] Blessed4aDay
[F1] robbie
[F1] UncleDooom

This is our monthly thread for new icons, NFT collections, and new dApps from existing providers. Please read the related [Notification of new programs announcements for already implemented providers](https://github.com/asastats/channel/discussions/130) to find out for which new dApps you should ping us. We won't be rewarding anymore for reporting an individual icon or dApp, we'll rather reward members' monthly activity.

Of course, for all the other providers or functionalities not listed in that discussion, a usual feature request issue should be created and rewarded accordingly. If a dApp isn't evaluated after a while even if you pinged us about it, we have a bug so please create a bug issue here.

**Comment by moloch10** [comment]
New token:

1387238831
GOAN

https://allo.info/asset/1387238831/token

**Comment by ipaleka** [comment]
[mochanerd](https://discord.com/channels/906917846754418770/908054304332603402/1212886404489543730) 

> Token logo request 🙏🏾 https://vestige.fi/asset/891226062

**Comment by ipaleka** [comment]
[mochanerd](https://discord.com/channels/906917846754418770/908054304332603402/1219474020001648740) 

> Token logo request! 🙏🏾 $BIGBOI https://allo.info/asset/1437818649/token

**Comment by Grinnmarr** [comment]
Token Icon please
https://vestige.fi/asset/1275370710

**Comment by ipaleka** [comment]
By mochanerd in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1223967198926602273):
> GM, Happy Easter, token logo request please! 🙏🏾 https://explorer.perawallet.app/asset/1642742254/

**Comment by ipaleka** [comment]
By mochanerd in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1224403794197086219):
> GM, token logo request: $DAFFIR  🙏🏾https://allo.info/asset/1268830233/token

**Comment by moloch10** [comment]
5MBNHIU4SH3QEO7TAJFHSE7NEKFDDCGP3HRPIXESZPKCEGEJDMCXRP2VZY - 6AM Macro
SS72W76UMWTLMRLTYTA4JP7MV7Q7KEAPFG3YUX6DSJQ7IIALJGVUCMNHO4 - A. Rex Baby 
BBH5DN4QNN66DIV2TZAQEXKOKZG4MND4X6NKB5VSJVH7LGSSCT4WU6OBEA - Algo Wolf
ANWUIETXQ3HOSQQPE4F7URM546HV72LA2OGS6ZVWDZBBAE6FAVS5E3UZHU - Algocoins
U5M2HEJSBXUNOD33PWGFPBUXMCDCF4FTM6DRGEANOII5MQM2MZLE4X4XUM - AlgoGenie
QKPWFZLBGVLOVUJMFWDPEXAIYCBMVOYTLONTEORI3JDBIDTN5SGBXBIBZY - Aliance Area
BOREDO6HFSCNSEJHW53MDTBBWHBBCPOZPDVXQ5EIC4G66UIBEABHH75NXY - Bored Alien Squad
Z7M7VB65YV6QXO3HM3BSVPTAPR27VQQXW53MTWJABY6QBJIEMC773Z7KCQ - GOBBI
CHWVH5L4HDPTNJGMF6356J7CUH2OPN4A36CTDZT53T34DJMVR2P33MR54Q - Knight of the Gods
BV4JZPDE4ZOARNIR5SPUP7AJ5LK7RT5277BWEHSSOJISLVBQKV3RUD3VXA - Luminaughties
B5X6OTS3AK523JL3GQOWVHEANM7D6OMNBUMTDUCAD43RB66ARECW2EYMIA - Meerkat
EXXEWCLDL73Z6HUCCM52KRPIRABF7RCBSJPAK2ICOQET5RGUA5YE6PTLFM - MicroFract
N6ANIBSUUXQMIR7C6UGJHCDZC5EDAXJ6XO2AH3JTPNDTRFHDAAZ44EXYV4 - Mutant Deer
LF5J27VXFMNZ5Z3JHBILIO6Q3XZOYCD7QQBXQ6GFUS3QBZBMZC463AUE5Q - Nostalgic Items
HAPY6X34PVU4O65OMD7FDQO3RA2GUIISHJOFUEAO2NOLQ6IJBOOBH5FHQA - SodaPopNFT
33T5UK5JT53UHY47BDVJFVI3B2OUU7IAMVQJHYOWU3N4EQOZLOBTCLSGLE - Unknown Blobs Unique
QSPIRT6PDVM3QXQATRYWHLDFTXNWTDAAOMEIAE6MXG74WJKHBXCTUTG4F4 - Yieldly Rank

**Comment by ipaleka** [comment]
By mochanerd in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1225963957332738090):
> Good evening, I have a token logo request please: $A200 🙏🏾 https://explorer.perawallet.app/asset/1682662165/

**Comment by kerrilija** [comment]
by Blessed4aDay in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1226996122229407874):

> afternoon! quick question.. does ASAStats pull data from PactFi for LP pools on the main dash board? It only seems to pick up Tinyman for me.. am I doing something wrong?

by robbie in [Discord](https://discord.com/channels/906917846754418770/908054330265960478/1226956167054360606):

> Never know where to ask, but there are a few new farms on pact. RWA/ALGO, COOP/ALGO and AKTA/ALGO

**Comment by moloch10** [comment]
By mochanerd in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1227254882289979492):

> $OTSDGFKD https://explorer.perawallet.app/asset/1699699699/

-----
> Token logo request to be impartial 🙏🏾: $OTSDHBVA https://allo.info/asset/1105062628/token

-----
> Token logo request 🙏🏾: $SWIFHAT https://explorer.perawallet.app/asset/1643242122/

-----
> Token logo request 🙏🏾: $CABAL https://explorer.perawallet.app/asset/1728597969/

**Comment by Grinnmarr** [comment]
Token icon request
https://vestige.fi/asset/1691166331

**Comment by Grinnmarr** [comment]
And another please
https://vestige.fi/asset/1182620971

**Comment by ipaleka** [comment]
By mochanerd in [Discord](https://discord.com/channels/906917846754418770/908054304332603402/1229752039865847859)
> Token logo request 🙏🏾: $RWA
> https://explorer.perawallet.app/asset/1721213788/

**Comment by ipaleka** [comment]
By UncleDooom in [Discord](https://discord.com/channels/906917846754418770/910524302531649566/1232799434505453659):
> https://vestige.fi/asset/1784383458
